const conhecer = [
  { text: "Filme favorito e por quê?" },
  { text: "Série que mais te marcou?" },
  { text: "Último filme que assistiu?" },
  { text: "Gênero de filme preferido?" },
  { text: "Música que nunca enjoa?" },
  { text: "Artista ou banda favorita?" },
  { text: "Livro favorito?" },
  { text: "Último livro que leu?" },
  { text: "Prefere cinema ou streaming?" },
  { text: "Prefere sair ou ficar em casa?" },
  { text: "Café ou chá?" },
  { text: "Doce ou salgado?" },
  { text: "Pizza ou hambúrguer?" },
  { text: "Comida favorita?" },
  { text: "Comida que você odeia?" },
  { text: "Restaurante preferido?" },
  { text: "Bebida favorita?" },
  { text: "Gosta de cozinhar?" },
  { text: "Prato que sabe fazer melhor?" },
  { text: "Música que te anima instantaneamente?" },
  { text: "Música que te acalma?" },
  { text: "Prefere praia ou montanha?" },
  { text: "Prefere frio ou calor?" },
  { text: "Gosta de esportes?" },
  { text: "Qual esporte acompanha?" },
  { text: "Qual esporte pratica?" },
  { text: "Hobbies atuais?" },
  { text: "Algo novo que gostaria de aprender?" },
  { text: "Jogo favorito?" },
  { text: "Prefere jogos de tabuleiro ou digitais?" },
  { text: "Como é um dia normal seu?" },
  { text: "A que horas costuma acordar?" },
  { text: "É mais produtivo de manhã ou à noite?" },
  { text: "Trabalha ou estuda com o quê?" },
  { text: "Gosta do que faz?" },
  { text: "O que te motivou a escolher essa área?" },
  { text: "Trabalha em casa ou presencial?" },
  { text: "Quantas vezes treina por semana?" },
  { text: "Prefere academia ou atividade ao ar livre?" },
  { text: "Costuma cozinhar ou pedir comida?" },
  { text: "Dorme bem?" },
  { text: "Quantas horas dorme em média?" },
  { text: "Usa muito o celular?" },
  { text: "Redes sociais favoritas?" },
  { text: "Usa mais WhatsApp ou Instagram?" },
  { text: "Gosta de rotina ou improviso?" },
  { text: "Prefere planejar ou decidir na hora?" },
  { text: "É organizado(a) ou bagunçado(a)?" },
  { text: "Trabalha melhor sob pressão?" },
  { text: "Como lida com estresse?" },
  { text: "Você se considera introvertido(a) ou extrovertido(a)?" },
  { text: "Prefere conversar ou ouvir?" },
  { text: "Se considera mais racional ou emocional?" },
  { text: "É paciente ou impulsivo(a)?" },
  { text: "O que mais te irrita?" },
  { text: "O que mais te faz rir?" },
  { text: "Algo que te deixa confortável rápido?" },
  { text: "Algo que te deixa desconfortável?" },
  { text: "Gosta de silêncio?" },
  { text: "Gosta de multidão?" },
  { text: "Prefere poucas amizades ou muitas?" },
  { text: "Se considera tímido(a)?" },
  { text: "Se considera comunicativo(a)?" },
  { text: "Como reage a críticas?" },
  { text: "O que mais valoriza em uma pessoa?" },
  { text: "Qual seu maior defeito?" },
  { text: "Qual sua maior qualidade?" },
  { text: "Algo que está tentando melhorar?" },
  { text: "Costuma guardar ou falar o que sente?" },
  { text: "Lida bem com mudanças?" },
  { text: "Prefere poucas pessoas próximas ou muitas?" },
  { text: "Valoriza mais lealdade ou sinceridade?" },
  { text: "Gosta de conversar sobre sentimentos?" },
  { text: "Resolve conflitos conversando ou se afastando?" },
  { text: "Gosta de demonstrações de carinho?" },
  { text: "Prefere resolver tudo na hora ou depois?" },
  { text: "O que te faz confiar em alguém?" },
  { text: "O que quebra sua confiança?" },
  { text: "Prefere relações intensas ou tranquilas?" },
  { text: "Gosta de surpresas?" },
  { text: "Gosta de planejar encontros?" },
  { text: "O que espera de uma boa amizade?" },
  { text: "Como demonstra carinho?" },
  { text: "Como gosta de receber carinho?" },
  { text: "Prefere qualidade ou quantidade de tempo juntos?" },
  { text: "Valoriza mais palavras ou atitudes?" },
  { text: "Gosta de conversas profundas?" },
  { text: "Gosta de conversas leves?" },
  { text: "Se apega fácil?" },
  { text: "Precisa de espaço pessoal?" },
  { text: "O que é sucesso para você?" },
  { text: "O que é felicidade para você?" },
  { text: "O que mais valoriza na vida?" },
  { text: "Dinheiro ou tempo?" },
  { text: "Estabilidade ou liberdade?" },
  { text: "Prefere segurança ou aventura?" },
  { text: "Acredita em sorte ou esforço?" },
  { text: "Algo que nunca abriria mão?" },
  { text: "Algo que mudou muito em você?" },
  { text: "Algo que aprendeu com o tempo?" },
  { text: "Qual valor você aprendeu em casa?" },
  { text: "Algo que admira nas pessoas?" },
  { text: "Algo que não tolera?" },
  { text: "O que te faz respeitar alguém?" },
  { text: "Acredita que pessoas mudam?" },
  { text: "Prefere conforto ou desafio?" },
  { text: "O que te motiva?" },
  { text: "O que te desmotiva?" },
  { text: "O que te dá orgulho?" },
  { text: "Algo que você defende com convicção?" },
  { text: "Onde cresceu?" },
  { text: "Como foi sua infância?" },
  { text: "Uma memória feliz?" },
  { text: "Uma memória marcante?" },
  { text: "Algo que aprendeu cedo?" },
  { text: "Algo que demorou a aprender?" },
  { text: "Um momento que te mudou?" },
  { text: "Um erro que virou aprendizado?" },
  { text: "Algo que faria diferente?" },
  { text: "Algo que repetiria?" },
  { text: "Uma viagem marcante?" },
  { text: "Uma fase difícil que superou?" },
  { text: "Algo que te moldou como pessoa?" },
  { text: "Um conselho que recebeu?" },
  { text: "Um conselho que daria?" },
  { text: "Algo que já te surpreendeu em você?" },
  { text: "Algo que já te decepcionou?" },
  { text: "Um desafio superado?" },
  { text: "Um medo que venceu?" },
  { text: "Um medo atual?" },
  { text: "Onde se vê em 5 anos?" },
  { text: "Onde se vê em 10 anos?" },
  { text: "Um sonho pessoal?" },
  { text: "Um sonho profissional?" },
  { text: "Algo que quer conquistar?" },
  { text: "Algo que quer aprender?" },
  { text: "Algo que quer mudar?" },
  { text: "Algo que quer manter?" },
  { text: "Um projeto futuro?" },
  { text: "Um objetivo atual?" },
  { text: "O que te impede hoje?" },
  { text: "O que te ajuda hoje?" },
  { text: "Um hábito que quer criar?" },
  { text: "Um hábito que quer largar?" },
  { text: "Algo que quer fazer ainda jovem?" },
  { text: "Algo que quer fazer sem pressa?" },
  { text: "Um medo sobre o futuro?" },
  { text: "Uma expectativa boa?" },
  { text: "Algo que te dá esperança?" },
  { text: "Algo que te preocupa?" },
  { text: "Top 3 lugares que gostaria de conhecer?" },
  { text: "Lugar favorito que já visitou?" },
  { text: "Prefere viagem curta ou longa?" },
  { text: "Prefere cidade ou natureza?" },
  { text: "Prefere hotel ou Airbnb?" },
  { text: "Prefere planejar ou improvisar viagem?" },
  { text: "Viagem sozinho(a) ou acompanhado(a)?" },
  { text: "Uma viagem dos sonhos?" },
  { text: "Algo que faria em outra cultura?" },
  { text: "Uma experiência inesquecível?" },
  { text: "Algo radical que faria?" },
  { text: "Algo que não faria?" },
  { text: "Algo simples que ama fazer?" },
  { text: "Algo que gostaria de experimentar?" },
  { text: "Algo que te tira da zona de conforto?" },
  { text: "Algo que te relaxa?" },
  { text: "Algo que te inspira?" },
  { text: "Algo que te recarrega?" },
  { text: "Algo que te cansa?" },
  { text: "Algo que te anima?" },
  { text: "Café da manhã ou jantar?" },
  { text: "Comer fora ou pedir delivery?" },
  { text: "Planejar ou improvisar?" },
  { text: "Ficar em casa ou sair?" },
  { text: "Dia ou noite?" },
  { text: "Verão ou inverno?" },
  { text: "Doce ou salgado?" },
  { text: "Filmes ou séries?" },
  { text: "Ler ou assistir?" },
  { text: "Academia ou caminhada?" },
  { text: "Música alta ou baixa?" },
  { text: "Mensagem ou ligação?" },
  { text: "Conversa curta ou longa?" },
  { text: "Conversa profunda ou leve?" },
  { text: "Agenda cheia ou livre?" },
  { text: "Silêncio ou som ambiente?" },
  { text: "Sozinho(a) ou acompanhado(a)?" },
  { text: "Organização ou flexibilidade?" },
  { text: "Economia ou conforto?" },
  { text: "Segurança ou risco?" },
  { text: "Conte algo que poucas pessoas sabem sobre você" },
  { text: "Mostre sua música favorita agora" },
  { text: "Conte algo que te faz sorrir fácil" },
  { text: "Conte algo que te dá orgulho" },
  { text: "Conte algo que quer melhorar" },
  { text: "Conte algo que te define hoje" },
  { text: "Conte algo que mudou em você" },
  { text: "Conte algo que você ama fazer" },
  { text: "Conte algo que odeia fazer" },
  { text: "Conte algo que te representa" },
  { text: "Para fechar a conversa" },
  { text: "O que mais gostou de conversar até agora?" },
  { text: "Algo que ficou curioso(a) em saber?" },
  { text: "Algo que gostaria de perguntar mas não perguntou?" },
  { text: "Algo que acha importante dizer?" },
  { text: "Algo que valoriza em conexões?" },
  { text: "Algo que espera das pessoas?" },
  { text: "Algo que te aproxima de alguém?" },
  { text: "Algo que te afasta de alguém?" },
  { text: "Algo que te faz sentir à vontade?" },
  { text: "Algo que te deixa desconfiado(a)?" },
  { text: "Algo que você aprendeu recentemente?" },
  { text: "Algo que mudou sua forma de pensar?" },
  { text: "Algo que te inspira hoje?" },
  { text: "Algo que te desafia hoje?" },
  { text: "Algo que te deixa tranquilo(a)?" },
  { text: "Algo que te deixa animado(a)?" },
  { text: "Algo que te faz querer continuar uma conversa?" },
  { text: "Algo que te faz perder interesse?" },
  { text: "Algo que valoriza em encontros?" },
  { text: "Algo que evita em encontros?" },
  { text: "Algo que considera essencial em uma boa conexão?" },
  { text: "Algo que considera superficial?" },
  { text: "Algo que considera profundo?" },
  { text: "Algo que te faz sentir ouvido(a)?" },
  { text: "Algo que te faz sentir visto(a)?" },
  { text: "Algo que te faz sentir confortável?" },
  { text: "Algo que te faz sentir seguro(a)?" },
  { text: "Algo que te faz sentir curioso(a)?" },
  { text: "Algo que te faz querer repetir?" },
  { text: "Algo que te faz querer encerrar?" },
  { text: "Como você gosta de começar uma conversa?" },
  { text: "Como gosta de terminar uma conversa?" },
  { text: "O que faz uma conversa fluir?" },
  { text: "O que trava uma conversa?" },
  { text: "O que mais te conecta com alguém?" },
  { text: "O que mais te distancia?" },
  { text: "O que você busca conhecer em alguém primeiro?" },
  { text: "O que você percebe rápido nas pessoas?" },
  { text: "Algo que você nota mas poucos percebem?" },
  { text: "Algo que você acha subestimado?" },
  { text: "Algo que você acha superestimado?" },
  { text: "Algo simples que te faz feliz?" },
  { text: "Algo complexo que te desafia?" },
  { text: "Algo que você leva para a vida?" },
  { text: "Algo que aprendeu com erros?" },
  { text: "Algo que aprendeu com acertos?" },
  { text: "Algo que ainda está aprendendo?" },
  { text: "Algo que quer compartilhar mais?" },
  { text: "Algo que quer guardar para si?" },
  { text: "O que te faria querer conhecer alguém melhor?" }
];

export default conhecer;