const conhecer = [
  "Filme favorito e por quê?",
  "Série que mais te marcou?",
  "Último filme que assistiu?",
  "Gênero de filme preferido?",
  "Música que nunca enjoa?",
  "Artista ou banda favorita?",
  "Livro favorito?",
  "Último livro que leu?",
  "Prefere cinema ou streaming?",
  "Prefere sair ou ficar em casa?",
  "Café ou chá?",
  "Doce ou salgado?",
  "Pizza ou hambúrguer?",
  "Comida favorita?",
  "Comida que você odeia?",
  "Restaurante preferido?",
  "Bebida favorita?",
  "Gosta de cozinhar?",
  "Prato que sabe fazer melhor?",
  "Música que te anima instantaneamente?",
  "Música que te acalma?",
  "Prefere praia ou montanha?",
  "Prefere frio ou calor?",
  "Gosta de esportes?",
  "Qual esporte acompanha?",
  "Qual esporte pratica?",
  "Hobbies atuais?",
  "Algo novo que gostaria de aprender?",
  "Jogo favorito?",
  "Prefere jogos de tabuleiro ou digitais?",
  "Como é um dia normal seu?",
  "A que horas costuma acordar?",
  "É mais produtivo de manhã ou à noite?",
  "Trabalha ou estuda com o quê?",
  "Gosta do que faz?",
  "O que te motivou a escolher essa área?",
  "Trabalha em casa ou presencial?",
  "Quantas vezes treina por semana?",
  "Prefere academia ou atividade ao ar livre?",
  "Costuma cozinhar ou pedir comida?",
  "Dorme bem?",
  "Quantas horas dorme em média?",
  "Usa muito o celular?",
  "Redes sociais favoritas?",
  "Usa mais WhatsApp ou Instagram?",
  "Gosta de rotina ou improviso?",
  "Prefere planejar ou decidir na hora?",
  "É organizado(a) ou bagunçado(a)?",
  "Trabalha melhor sob pressão?",
  "Como lida com estresse?",
  "Você se considera introvertido(a) ou extrovertido(a)?",
  "Prefere conversar ou ouvir?",
  "Se considera mais racional ou emocional?",
  "É paciente ou impulsivo(a)?",
  "O que mais te irrita?",
  "O que mais te faz rir?",
  "Algo que te deixa confortável rápido?",
  "Algo que te deixa desconfortável?",
  "Gosta de silêncio?",
  "Gosta de multidão?",
  "Prefere poucas amizades ou muitas?",
  "Se considera tímido(a)?",
  "Se considera comunicativo(a)?",
  "Como reage a críticas?",
  "O que mais valoriza em uma pessoa?",
  "Qual seu maior defeito?",
  "Qual sua maior qualidade?",
  "Algo que está tentando melhorar?",
  "Costuma guardar ou falar o que sente?",
  "Lida bem com mudanças?",
  "Prefere poucas pessoas próximas ou muitas?",
  "Valoriza mais lealdade ou sinceridade?",
  "Gosta de conversar sobre sentimentos?",
  "Resolve conflitos conversando ou se afastando?",
  "Gosta de demonstrações de carinho?",
  "Prefere resolver tudo na hora ou depois?",
  "O que te faz confiar em alguém?",
  "O que quebra sua confiança?",
  "Prefere relações intensas ou tranquilas?",
  "Gosta de surpresas?",
  "Gosta de planejar encontros?",
  "O que espera de uma boa amizade?",
  "Como demonstra carinho?",
  "Como gosta de receber carinho?",
  "Prefere qualidade ou quantidade de tempo juntos?",
  "Valoriza mais palavras ou atitudes?",
  "Gosta de conversas profundas?",
  "Gosta de conversas leves?",
  "Se apega fácil?",
  "Precisa de espaço pessoal?",
  "O que é sucesso para você?",
  "O que é felicidade para você?",
  "O que mais valoriza na vida?",
  "Dinheiro ou tempo?",
  "Estabilidade ou liberdade?",
  "Prefere segurança ou aventura?",
  "Acredita em sorte ou esforço?",
  "Algo que nunca abriria mão?",
  "Algo que mudou muito em você?",
  "Algo que aprendeu com o tempo?",
  "Qual valor você aprendeu em casa?",
  "Algo que admira nas pessoas?",
  "Algo que não tolera?",
  "O que te faz respeitar alguém?",
  "Acredita que pessoas mudam?",
  "Prefere conforto ou desafio?",
  "O que te motiva?",
  "O que te desmotiva?",
  "O que te dá orgulho?",
  "Algo que você defende com convicção?",
  "Onde cresceu?",
  "Como foi sua infância?",
  "Uma memória feliz?",
  "Uma memória marcante?",
  "Algo que aprendeu cedo?",
  "Algo que demorou a aprender?",
  "Um momento que te mudou?",
  "Um erro que virou aprendizado?",
  "Algo que faria diferente?",
  "Algo que repetiria?",
  "Uma viagem marcante?",
  "Uma fase difícil que superou?",
  "Algo que te moldou como pessoa?",
  "Um conselho que recebeu?",
  "Um conselho que daria?",
  "Algo que já te surpreendeu em você?",
  "Algo que já te decepcionou?",
  "Um desafio superado?",
  "Um medo que venceu?",
  "Um medo atual?",
  "Onde se vê em 5 anos?",
  "Onde se vê em 10 anos?",
  "Um sonho pessoal?",
  "Um sonho profissional?",
  "Algo que quer conquistar?",
  "Algo que quer aprender?",
  "Algo que quer mudar?",
  "Algo que quer manter?",
  "Um projeto futuro?",
  "Um objetivo atual?",
  "O que te impede hoje?",
  "O que te ajuda hoje?",
  "Um hábito que quer criar?",
  "Um hábito que quer largar?",
  "Algo que quer fazer ainda jovem?",
  "Algo que quer fazer sem pressa?",
  "Um medo sobre o futuro?",
  "Uma expectativa boa?",
  "Algo que te dá esperança?",
  "Algo que te preocupa?",
  "Top 3 lugares que gostaria de conhecer?",
  "Lugar favorito que já visitou?",
  "Prefere viagem curta ou longa?",
  "Prefere cidade ou natureza?",
  "Prefere hotel ou Airbnb?",
  "Prefere planejar ou improvisar viagem?",
  "Viagem sozinho(a) ou acompanhado(a)?",
  "Uma viagem dos sonhos?",
  "Algo que faria em outra cultura?",
  "Uma experiência inesquecível?",
  "Algo radical que faria?",
  "Algo que não faria?",
  "Algo simples que ama fazer?",
  "Algo que gostaria de experimentar?",
  "Algo que te tira da zona de conforto?",
  "Algo que te relaxa?",
  "Algo que te inspira?",
  "Algo que te recarrega?",
  "Algo que te cansa?",
  "Algo que te anima?",
  "Café da manhã ou jantar?",
  "Comer fora ou pedir delivery?",
  "Planejar ou improvisar?",
  "Ficar em casa ou sair?",
  "Dia ou noite?",
  "Verão ou inverno?",
  "Doce ou salgado?",
  "Filmes ou séries?",
  "Ler ou assistir?",
  "Academia ou caminhada?",
  "Música alta ou baixa?",
  "Mensagem ou ligação?",
  "Conversa curta ou longa?",
  "Conversa profunda ou leve?",
  "Agenda cheia ou livre?",
  "Silêncio ou som ambiente?",
  "Sozinho(a) ou acompanhado(a)?",
  "Organização ou flexibilidade?",
  "Economia ou conforto?",
  "Segurança ou risco?",
  "Conte algo que poucas pessoas sabem sobre você",
  "Mostre sua música favorita agora",
  "Conte algo que te faz sorrir fácil",
  "Conte algo que te dá orgulho",
  "Conte algo que quer melhorar",
  "Conte algo que te define hoje",
  "Conte algo que mudou em você",
  "Conte algo que você ama fazer",
  "Conte algo que odeia fazer",
  "Conte algo que te representa",
  "Para fechar a conversa",
  "O que mais gostou de conversar até agora?",
  "Algo que ficou curioso(a) em saber?",
  "Algo que gostaria de perguntar mas não perguntou?",
  "Algo que acha importante dizer?",
  "Algo que valoriza em conexões?",
  "Algo que espera das pessoas?",
  "Algo que te aproxima de alguém?",
  "Algo que te afasta de alguém?",
  "Algo que te faz sentir à vontade?",
  "Algo que te deixa desconfiado(a)?",
  "Algo que você aprendeu recentemente?",
  "Algo que mudou sua forma de pensar?",
  "Algo que te inspira hoje?",
  "Algo que te desafia hoje?",
  "Algo que te deixa tranquilo(a)?",
  "Algo que te deixa animado(a)?",
  "Algo que te faz querer continuar uma conversa?",
  "Algo que te faz perder interesse?",
  "Algo que valoriza em encontros?",
  "Algo que evita em encontros?",
  "Algo que considera essencial em uma boa conexão?",
  "Algo que considera superficial?",
  "Algo que considera profundo?",
  "Algo que te faz sentir ouvido(a)?",
  "Algo que te faz sentir visto(a)?",
  "Algo que te faz sentir confortável?",
  "Algo que te faz sentir seguro(a)?",
  "Algo que te faz sentir curioso(a)?",
  "Algo que te faz querer repetir?",
  "Algo que te faz querer encerrar?",
  "Como você gosta de começar uma conversa?",
  "Como gosta de terminar uma conversa?",
  "O que faz uma conversa fluir?",
  "O que trava uma conversa?",
  "O que mais te conecta com alguém?",
  "O que mais te distancia?",
  "O que você busca conhecer em alguém primeiro?",
  "O que você percebe rápido nas pessoas?",
  "Algo que você nota mas poucos percebem?",
  "Algo que você acha subestimado?",
  "Algo que você acha superestimado?",
  "Algo simples que te faz feliz?",
  "Algo complexo que te desafia?",
  "Algo que você leva para a vida?",
  "Algo que aprendeu com erros?",
  "Algo que aprendeu com acertos?",
  "Algo que ainda está aprendendo?",
  "Algo que quer compartilhar mais?",
  "Algo que quer guardar para si?",
  "O que te faria querer conhecer alguém melhor?"
];

export default conhecer;