const euNunca = [
  "Eu nunca tive nada inserido no meu ânus",
  "Eu nunca usei nenhum injetável",
  "Eu nunca transei com uma amiga(o)",
  "Eu nunca entrei em coma",
  "Eu nunca dei PT",
  "Eu nunca matei aula",
  "Eu nunca saí do país",
  "Eu nunca fui à praia",
  "Eu nunca dormi em uma praça",
  "Eu nunca transei bêbado",
  "Eu nunca transei chapado",
  "Eu nunca mandei nude",
  "Eu nunca recebi nude",
  "Eu nunca mandei nude para a pessoa errada",
  "Eu nunca fui pego(a) me masturbando",
  "Eu nunca fiz sexo casual",
  "Eu nunca fiz sexo no primeiro encontro",
  "Eu nunca fiz sexo em local público",
  "Eu nunca fiz sexo no carro",
  "Eu nunca fiz sexo em banheiro público",
  "Eu nunca fiz sexo em casa alheia",
  "Eu nunca fiz sexo escondido",
  "Eu nunca fiz sexo com alguém comprometido",
  "Eu nunca traí",
  "Eu nunca fui traído(a)",
  "Eu nunca fiquei com ex",
  "Eu nunca fiquei com ex de amigo(a)",
  "Eu nunca fiquei com alguém do trabalho",
  "Eu nunca fiquei com alguém só por carência",
  "Eu nunca fiquei com alguém por interesse",
  "Eu nunca menti sobre meu passado sexual",
  "Eu nunca fingi orgasmo",
  "Eu nunca broxei",
  "Eu nunca fiz algo sexual que me arrependo",
  "Eu nunca tive fetiche estranho",
  "Eu nunca escondi um fetiche",
  "Eu nunca tive curiosidade sexual fora do padrão",
  "Eu nunca usei brinquedo sexual",
  "Eu nunca quis experimentar algo diferente na cama",
  "Eu nunca tive vontade de transar com alguém proibido",
  "Eu nunca usei drogas ilícitas",
  "Eu nunca fumei maconha",
  "Eu nunca cheirei pó",
  "Eu nunca usei droga sintética",
  "Eu nunca misturei drogas",
  "Eu nunca misturei álcool com remédio",
  "Eu nunca apaguei de tanto beber",
  "Eu nunca acordei sem lembrar da noite anterior",
  "Eu nunca passei mal por beber demais",
  "Eu nunca bebi escondido",
  "Eu nunca roubei algo",
  "Eu nunca furtei em loja",
  "Eu nunca falsifiquei assinatura",
  "Eu nunca menti para a polícia",
  "Eu nunca fui parado(a) pela polícia",
  "Eu nunca fui detido(a)",
  "Eu nunca fui algemado(a)",
  "Eu nunca tive problemas com a justiça",
  "Eu nunca dirigi bêbado(a)",
  "Eu nunca dirigi sem habilitação",
  "Eu nunca colei em prova",
  "Eu nunca paguei alguém para fazer trabalho",
  "Eu nunca plagiei",
  "Eu nunca faltei trabalho sem motivo",
  "Eu nunca menti para chefe",
  "Eu nunca fingi estar doente",
  "Eu nunca dormi no trabalho",
  "Eu nunca fui demitido(a)",
  "Eu nunca pedi demissão por raiva",
  "Eu nunca odiei um colega de trabalho",
  "Eu nunca stalkeei alguém",
  "Eu nunca stalkeei ex",
  "Eu nunca usei fake para stalkear",
  "Eu nunca criei perfil fake",
  "Eu nunca menti na internet",
  "Eu nunca deletei mensagem comprometedora",
  "Eu nunca apaguei conversa para esconder algo",
  "Eu nunca invadi privacidade de alguém",
  "Eu nunca li conversa alheia",
  "Eu nunca mexi no celular de alguém escondido",
  "Eu nunca briguei fisicamente",
  "Eu nunca apanhei",
  "Eu nunca bati em alguém",
  "Eu nunca causei confusão em público",
  "Eu nunca fui expulso(a) de um lugar",
  "Eu nunca fui barrado(a) em festa",
  "Eu nunca fui humilhado(a) em público",
  "Eu nunca humilhei alguém",
  "Eu nunca falei algo que me arrependi",
  "Eu nunca perdi amizade por besteira",
  "Eu nunca chorei por alguém que não valia a pena",
  "Eu nunca corri atrás de quem não queria nada",
  "Eu nunca me humilhei por ex",
  "Eu nunca implorei por atenção",
  "Eu nunca bloqueei alguém e desbloqueei depois",
  "Eu nunca stalkeei depois de bloquear",
  "Eu nunca terminei por mensagem",
  "Eu nunca ghosteei alguém",
  "Eu nunca fui ghosteado(a)",
  "Eu nunca fiquei obcecado(a) por alguém",
  "Eu nunca menti sobre minha idade",
  "Eu nunca menti sobre renda",
  "Eu nunca menti sobre sentimentos",
  "Eu nunca manipulei alguém",
  "Eu nunca fui manipulado(a)",
  "Eu nunca fiz drama para conseguir algo",
  "Eu nunca usei alguém",
  "Eu nunca me senti usado(a)",
  "Eu nunca tive crise de ciúmes",
  "Eu nunca fui tóxico(a)",
  "Eu nunca pensei em sumir",
  "Eu nunca quis largar tudo",
  "Eu nunca tive crise existencial",
  "Eu nunca me senti perdido(a)",
  "Eu nunca odiei minha vida em algum momento",
  "Eu nunca me comparei com todo mundo",
  "Eu nunca invejei alguém",
  "Eu nunca desejei a vida de outra pessoa",
  "Eu nunca me senti insuficiente",
  "Eu nunca fingi estar bem",
  "Eu nunca dormi na rua",
  "Eu nunca dormi em casa desconhecida",
  "Eu nunca viajei sem planejar",
  "Eu nunca perdi voo",
  "Eu nunca perdi ônibus",
  "Eu nunca me perdi em outra cidade",
  "Eu nunca passei perrengue em viagem",
  "Eu nunca fui enganado(a) em viagem",
  "Eu nunca fiz algo ilegal em viagem",
  "Eu nunca voltei quebrado(a) financeiramente",
  "Eu nunca gastei dinheiro que não tinha",
  "Eu nunca fiquei endividado(a)",
  "Eu nunca escondi dívida",
  "Eu nunca emprestei dinheiro e me ferrei",
  "Eu nunca pedi dinheiro emprestado",
  "Eu nunca gastei tudo em besteira",
  "Eu nunca fiz compra por impulso",
  "Eu nunca me arrependi de compra cara",
  "Eu nunca comprei algo só por status",
  "Eu nunca vendi algo meu por necessidade",
  "Eu nunca fui cancelado(a)",
  "Eu nunca cancelei alguém",
  "Eu nunca falei mal de alguém pelas costas",
  "Eu nunca fui falso(a)",
  "Eu nunca traí confiança",
  "Eu nunca fui traído(a) por amigo",
  "Eu nunca julguei alguém errado",
  "Eu nunca mudei opinião drasticamente",
  "Eu nunca fui hipócrita",
  "Eu nunca neguei algo óbvio",
  "Eu nunca experimentei algo só por curiosidade",
  "Eu nunca fiz algo só para provar algo",
  "Eu nunca fui influenciado(a) facilmente",
  "Eu nunca fui contra meus valores",
  "Eu nunca quebrei promessa",
  "Eu nunca fiz algo que escondo até hoje",
  "Eu nunca tenho um segredo pesado",
  "Eu nunca guardo culpa",
  "Eu nunca tenho medo de alguém descobrir algo",
  "Eu nunca vivi uma vida dupla",
  "Eu nunca passei vergonha em público",
  "Eu nunca paguei mico",
  "Eu nunca fiz algo bêbado que viralizou",
  "Eu nunca me arrependi no dia seguinte",
  "Eu nunca fiz algo e pensei “por que fiz isso?”",
  "Eu nunca fui lembrado(a) por algo vergonhoso",
  "Eu nunca fui zoado(a) por algo sério",
  "Eu nunca ri de coisa errada",
  "Eu nunca ri em momento inadequado",
  "Eu nunca fui inconveniente",
  "Eu nunca pensei em cometer um crime",
  "Eu nunca tive vontade de quebrar algo",
  "Eu nunca tive vontade de sumir do mapa",
  "Eu nunca quis mudar de identidade",
  "Eu nunca quis recomeçar do zero",
  "Eu nunca quis viver outra vida",
  "Eu nunca pensei “foda-se tudo”",
  "Eu nunca fiz algo sem pensar nas consequências",
  "Eu nunca me senti fora do controle",
  "Eu nunca perdi totalmente a noção",
  "Eu nunca tive medo real de morrer",
  "Eu nunca quase morri",
  "Eu nunca fui internado(a)",
  "Eu nunca fiz cirurgia",
  "Eu nunca quebrei um osso",
  "Eu nunca desmaiei",
  "Eu nunca tive crise de pânico",
  "Eu nunca tive medo de enlouquecer",
  "Eu nunca precisei de ajuda profissional",
  "Eu nunca ignorei sinais claros",
  "Eu nunca tive recaída",
  "Eu nunca voltei atrás em decisão",
  "Eu nunca insisti no erro",
  "Eu nunca aprendi do jeito difícil",
  "Eu nunca ignorei conselho",
  "Eu nunca me achei mais esperto(a) que todo mundo",
  "Eu nunca subestimei alguém",
  "Eu nunca superestimei alguém",
  "Eu nunca quebrei a cara feio",
  "Eu nunca aprendi algo na marra",
  "Eu nunca fiquei com alguém só por vingança",
  "Eu nunca usei alguém para esquecer outro",
  "Eu nunca fiz ciúmes de propósito",
  "Eu nunca menti dizendo que superei",
  "Eu nunca mantive contato por apego",
  "Eu nunca fiquei por medo de ficar só",
  "Eu nunca forcei sentimento",
  "Eu nunca me forcei a gostar",
  "Eu nunca fui embora tarde demais",
  "Eu nunca fiquei quando devia ir",
  "Eu nunca quis algo proibido",
  "Eu nunca tive fantasia estranha",
  "Eu nunca pensei “isso não é normal”",
  "Eu nunca gostei de algo que escondo",
  "Eu nunca me questionei profundamente",
  "Eu nunca mudei completamente",
  "Eu nunca senti que amadureci",
  "Eu nunca senti que regredi",
  "Eu nunca tive crise de identidade",
  "Eu nunca me senti outra pessoa",
  "Eu nunca fui feliz por pouco tempo",
  "Eu nunca estraguei algo bom",
  "Eu nunca sabotei algo",
  "Eu nunca tive medo de dar certo",
  "Eu nunca tive medo de fracassar",
  "Eu nunca fugi de oportunidade",
  "Eu nunca perdi chance por medo",
  "Eu nunca me arrependi de tentar",
  "Eu nunca me arrependi de não tentar",
  "Eu nunca senti que perdi tempo",
  "Eu nunca me senti deslocado(a)",
  "Eu nunca me senti em casa",
  "Eu nunca senti conexão instantânea",
  "Eu nunca senti conexão falsa",
  "Eu nunca confundi carência com amor",
  "Eu nunca confundi tesão com amor",
  "Eu nunca confundi amizade com interesse",
  "Eu nunca confundi liberdade com solidão",
  "Eu nunca confundi conforto com estagnação",
  "Eu nunca confundi intensidade com amor",
  "Eu nunca me expus demais",
  "Eu nunca me fechei demais",
  "Eu nunca confiei demais",
  "Eu nunca desconfiei demais",
  "Eu nunca vivi algo intenso",
  "Eu nunca vivi algo vazio",
  "Eu nunca vivi algo que me marcou",
  "Eu nunca vivi algo que me mudou",
  "Eu nunca vivi algo que me feriu",
  "Eu nunca vivi algo que me salvou"
];

export default euNunca;