const euNunca = [
  { text: "Eu nunca tive nada inserido no meu ânus" },
  { text: "Eu nunca usei nenhum injetável" },
  { text: "Eu nunca transei com uma amiga(o)" },
  { text: "Eu nunca entrei em coma" },
  { text: "Eu nunca dei PT" },
  { text: "Eu nunca matei aula" },
  { text: "Eu nunca saí do país" },
  { text: "Eu nunca fui à praia" },
  { text: "Eu nunca dormi em uma praça" },
  { text: "Eu nunca transei bêbado" },
  { text: "Eu nunca transei chapado" },
  { text: "Eu nunca mandei nude" },
  { text: "Eu nunca recebi nude" },
  { text: "Eu nunca mandei nude para a pessoa errada" },
  { text: "Eu nunca fui pego(a) me masturbando" },
  { text: "Eu nunca fiz sexo casual" },
  { text: "Eu nunca fiz sexo no primeiro encontro" },
  { text: "Eu nunca fiz sexo em local público" },
  { text: "Eu nunca fiz sexo no carro" },
  { text: "Eu nunca fiz sexo em banheiro público" },
  { text: "Eu nunca fiz sexo em casa alheia" },
  { text: "Eu nunca fiz sexo escondido" },
  { text: "Eu nunca fiz sexo com alguém comprometido" },
  { text: "Eu nunca traí" },
  { text: "Eu nunca fui traído(a)" },
  { text: "Eu nunca fiquei com ex" },
  { text: "Eu nunca fiquei com ex de amigo(a)" },
  { text: "Eu nunca fiquei com alguém do trabalho" },
  { text: "Eu nunca fiquei com alguém só por carência" },
  { text: "Eu nunca fiquei com alguém por interesse" },
  { text: "Eu nunca menti sobre meu passado sexual" },
  { text: "Eu nunca fingi orgasmo" },
  { text: "Eu nunca broxei" },
  { text: "Eu nunca fiz algo sexual que me arrependo" },
  { text: "Eu nunca tive fetiche estranho" },
  { text: "Eu nunca escondi um fetiche" },
  { text: "Eu nunca tive curiosidade sexual fora do padrão" },
  { text: "Eu nunca usei brinquedo sexual" },
  { text: "Eu nunca quis experimentar algo diferente na cama" },
  { text: "Eu nunca tive vontade de transar com alguém proibido" },
  { text: "Eu nunca usei drogas ilícitas" },
  { text: "Eu nunca fumei maconha" },
  { text: "Eu nunca cheirei pó" },
  { text: "Eu nunca usei droga sintética" },
  { text: "Eu nunca misturei drogas" },
  { text: "Eu nunca misturei álcool com remédio" },
  { text: "Eu nunca apaguei de tanto beber" },
  { text: "Eu nunca acordei sem lembrar da noite anterior" },
  { text: "Eu nunca passei mal por beber demais" },
  { text: "Eu nunca bebi escondido" },
  { text: "Eu nunca roubei algo" },
  { text: "Eu nunca furtei em loja" },
  { text: "Eu nunca falsifiquei assinatura" },
  { text: "Eu nunca menti para a polícia" },
  { text: "Eu nunca fui parado(a) pela polícia" },
  { text: "Eu nunca fui detido(a)" },
  { text: "Eu nunca fui algemado(a)" },
  { text: "Eu nunca tive problemas com a justiça" },
  { text: "Eu nunca dirigi bêbado(a)" },
  { text: "Eu nunca dirigi sem habilitação" },
  { text: "Eu nunca colei em prova" },
  { text: "Eu nunca paguei alguém para fazer trabalho" },
  { text: "Eu nunca plagiei" },
  { text: "Eu nunca faltei trabalho sem motivo" },
  { text: "Eu nunca menti para chefe" },
  { text: "Eu nunca fingi estar doente" },
  { text: "Eu nunca dormi no trabalho" },
  { text: "Eu nunca fui demitido(a)" },
  { text: "Eu nunca pedi demissão por raiva" },
  { text: "Eu nunca odiei um colega de trabalho" },
  { text: "Eu nunca stalkeei alguém" },
  { text: "Eu nunca stalkeei ex" },
  { text: "Eu nunca usei fake para stalkear" },
  { text: "Eu nunca criei perfil fake" },
  { text: "Eu nunca menti na internet" },
  { text: "Eu nunca deletei mensagem comprometedora" },
  { text: "Eu nunca apaguei conversa para esconder algo" },
  { text: "Eu nunca invadi privacidade de alguém" },
  { text: "Eu nunca li conversa alheia" },
  { text: "Eu nunca mexi no celular de alguém escondido" },
  { text: "Eu nunca briguei fisicamente" },
  { text: "Eu nunca apanhei" },
  { text: "Eu nunca bati em alguém" },
  { text: "Eu nunca causei confusão em público" },
  { text: "Eu nunca fui expulso(a) de um lugar" },
  { text: "Eu nunca fui barrado(a) em festa" },
  { text: "Eu nunca fui humilhado(a) em público" },
  { text: "Eu nunca humilhei alguém" },
  { text: "Eu nunca falei algo que me arrependi" },
  { text: "Eu nunca perdi amizade por besteira" },
  { text: "Eu nunca chorei por alguém que não valia a pena" },
  { text: "Eu nunca corri atrás de quem não queria nada" },
  { text: "Eu nunca me humilhei por ex" },
  { text: "Eu nunca implorei por atenção" },
  { text: "Eu nunca bloqueei alguém e desbloqueei depois" },
  { text: "Eu nunca stalkeei depois de bloquear" },
  { text: "Eu nunca terminei por mensagem" },
  { text: "Eu nunca ghosteei alguém" },
  { text: "Eu nunca fui ghosteado(a)" },
  { text: "Eu nunca fiquei obcecado(a) por alguém" },
  { text: "Eu nunca menti sobre minha idade" },
  { text: "Eu nunca menti sobre renda" },
  { text: "Eu nunca menti sobre sentimentos" },
  { text: "Eu nunca manipulei alguém" },
  { text: "Eu nunca fui manipulado(a)" },
  { text: "Eu nunca fiz drama para conseguir algo" },
  { text: "Eu nunca usei alguém" },
  { text: "Eu nunca me senti usado(a)" },
  { text: "Eu nunca tive crise de ciúmes" },
  { text: "Eu nunca fui tóxico(a)" },
  { text: "Eu nunca pensei em sumir" },
  { text: "Eu nunca quis largar tudo" },
  { text: "Eu nunca tive crise existencial" },
  { text: "Eu nunca me senti perdido(a)" },
  { text: "Eu nunca odiei minha vida em algum momento" },
  { text: "Eu nunca me comparei com todo mundo" },
  { text: "Eu nunca invejei alguém" },
  { text: "Eu nunca desejei a vida de outra pessoa" },
  { text: "Eu nunca me senti insuficiente" },
  { text: "Eu nunca fingi estar bem" },
  { text: "Eu nunca dormi na rua" },
  { text: "Eu nunca dormi em casa desconhecida" },
  { text: "Eu nunca viajei sem planejar" },
  { text: "Eu nunca perdi voo" },
  { text: "Eu nunca perdi ônibus" },
  { text: "Eu nunca me perdi em outra cidade" },
  { text: "Eu nunca passei perrengue em viagem" },
  { text: "Eu nunca fui enganado(a) em viagem" },
  { text: "Eu nunca fiz algo ilegal em viagem" },
  { text: "Eu nunca voltei quebrado(a) financeiramente" },
  { text: "Eu nunca gastei dinheiro que não tinha" },
  { text: "Eu nunca fiquei endividado(a)" },
  { text: "Eu nunca escondi dívida" },
  { text: "Eu nunca emprestei dinheiro e me ferrei" },
  { text: "Eu nunca pedi dinheiro emprestado" },
  { text: "Eu nunca gastei tudo em besteira" },
  { text: "Eu nunca fiz compra por impulso" },
  { text: "Eu nunca me arrependi de compra cara" },
  { text: "Eu nunca comprei algo só por status" },
  { text: "Eu nunca vendi algo meu por necessidade" },
  { text: "Eu nunca fui cancelado(a)" },
  { text: "Eu nunca cancelei alguém" },
  { text: "Eu nunca falei mal de alguém pelas costas" },
  { text: "Eu nunca fui falso(a)" },
  { text: "Eu nunca traí confiança" },
  { text: "Eu nunca fui traído(a) por amigo" },
  { text: "Eu nunca julguei alguém errado" },
  { text: "Eu nunca mudei opinião drasticamente" },
  { text: "Eu nunca fui hipócrita" },
  { text: "Eu nunca neguei algo óbvio" },
  { text: "Eu nunca experimentei algo só por curiosidade" },
  { text: "Eu nunca fiz algo só para provar algo" },
  { text: "Eu nunca fui influenciado(a) facilmente" },
  { text: "Eu nunca fui contra meus valores" },
  { text: "Eu nunca quebrei promessa" },
  { text: "Eu nunca fiz algo que escondo até hoje" },
  { text: "Eu nunca tenho um segredo pesado" },
  { text: "Eu nunca guardo culpa" },
  { text: "Eu nunca tenho medo de alguém descobrir algo" },
  { text: "Eu nunca vivi uma vida dupla" },
  { text: "Eu nunca passei vergonha em público" },
  { text: "Eu nunca paguei mico" },
  { text: "Eu nunca fiz algo bêbado que viralizou" },
  { text: "Eu nunca me arrependi no dia seguinte" },
  { text: "Eu nunca fiz algo e pensei “por que fiz isso?”" },
  { text: "Eu nunca fui lembrado(a) por algo vergonhoso" },
  { text: "Eu nunca fui zoado(a) por algo sério" },
  { text: "Eu nunca ri de coisa errada" },
  { text: "Eu nunca ri em momento inadequado" },
  { text: "Eu nunca fui inconveniente" },
  { text: "Eu nunca pensei em cometer um crime" },
  { text: "Eu nunca tive vontade de quebrar algo" },
  { text: "Eu nunca tive vontade de sumir do mapa" },
  { text: "Eu nunca quis mudar de identidade" },
  { text: "Eu nunca quis recomeçar do zero" },
  { text: "Eu nunca quis viver outra vida" },
  { text: "Eu nunca pensei “foda-se tudo”" },
  { text: "Eu nunca fiz algo sem pensar nas consequências" },
  { text: "Eu nunca me senti fora do controle" },
  { text: "Eu nunca perdi totalmente a noção" },
  { text: "Eu nunca tive medo real de morrer" },
  { text: "Eu nunca quase morri" },
  { text: "Eu nunca fui internado(a)" },
  { text: "Eu nunca fiz cirurgia" },
  { text: "Eu nunca quebrei um osso" },
  { text: "Eu nunca desmaiei" },
  { text: "Eu nunca tive crise de pânico" },
  { text: "Eu nunca tive medo de enlouquecer" },
  { text: "Eu nunca precisei de ajuda profissional" },
  { text: "Eu nunca ignorei sinais claros" },
  { text: "Eu nunca tive recaída" },
  { text: "Eu nunca voltei atrás em decisão" },
  { text: "Eu nunca insisti no erro" },
  { text: "Eu nunca aprendi do jeito difícil" },
  { text: "Eu nunca ignorei conselho" },
  { text: "Eu nunca me achei mais esperto(a) que todo mundo" },
  { text: "Eu nunca subestimei alguém" },
  { text: "Eu nunca superestimei alguém" },
  { text: "Eu nunca quebrei a cara feio" },
  { text: "Eu nunca aprendi algo na marra" },
  { text: "Eu nunca fiquei com alguém só por vingança" },
  { text: "Eu nunca usei alguém para esquecer outro" },
  { text: "Eu nunca fiz ciúmes de propósito" },
  { text: "Eu nunca menti dizendo que superei" },
  { text: "Eu nunca mantive contato por apego" },
  { text: "Eu nunca fiquei por medo de ficar só" },
  { text: "Eu nunca forcei sentimento" },
  { text: "Eu nunca me forcei a gostar" },
  { text: "Eu nunca fui embora tarde demais" },
  { text: "Eu nunca fiquei quando devia ir" },
  { text: "Eu nunca quis algo proibido" },
  { text: "Eu nunca tive fantasia estranha" },
  { text: "Eu nunca pensei “isso não é normal”" },
  { text: "Eu nunca gostei de algo que escondo" },
  { text: "Eu nunca me questionei profundamente" },
  { text: "Eu nunca mudei completamente" },
  { text: "Eu nunca senti que amadureci" },
  { text: "Eu nunca senti que regredi" },
  { text: "Eu nunca tive crise de identidade" },
  { text: "Eu nunca me senti outra pessoa" },
  { text: "Eu nunca fui feliz por pouco tempo" },
  { text: "Eu nunca estraguei algo bom" },
  { text: "Eu nunca sabotei algo" },
  { text: "Eu nunca tive medo de dar certo" },
  { text: "Eu nunca tive medo de fracassar" },
  { text: "Eu nunca fugi de oportunidade" },
  { text: "Eu nunca perdi chance por medo" },
  { text: "Eu nunca me arrependi de tentar" },
  { text: "Eu nunca me arrependi de não tentar" },
  { text: "Eu nunca senti que perdi tempo" },
  { text: "Eu nunca me senti deslocado(a)" },
  { text: "Eu nunca me senti em casa" },
  { text: "Eu nunca senti conexão instantânea" },
  { text: "Eu nunca senti conexão falsa" },
  { text: "Eu nunca confundi carência com amor" },
  { text: "Eu nunca confundi tesão com amor" },
  { text: "Eu nunca confundi amizade com interesse" },
  { text: "Eu nunca confundi liberdade com solidão" },
  { text: "Eu nunca confundi conforto com estagnação" },
  { text: "Eu nunca confundi intensidade com amor" },
  { text: "Eu nunca me expus demais" },
  { text: "Eu nunca me fechei demais" },
  { text: "Eu nunca confiei demais" },
  { text: "Eu nunca desconfiei demais" },
  { text: "Eu nunca vivi algo intenso" },
  { text: "Eu nunca vivi algo vazio" },
  { text: "Eu nunca vivi algo que me marcou" },
  { text: "Eu nunca vivi algo que me mudou" },
  { text: "Eu nunca vivi algo que me feriu" },
  { text: "Eu nunca vivi algo que me salvou" }
];

export default euNunca;