const galera = [
  { text: "Você pode cometer um crime sem ser condenado. Qual seria?" },
  { text: "Você pode apagar um país do mapa. Qual?" },
  { text: "Você pode destruir um lugar no mundo. Qual?" },
  { text: "Você pode mudar uma lei absurda. Qual?" },
  { text: "Você pode criar uma lei inútil. Qual?" },
  { text: "Você pode proibir algo comum. O quê?" },
  { text: "Você pode obrigar todo mundo a fazer algo estranho. O quê?" },
  { text: "Você pode escolher uma regra para a humanidade. Qual?" },
  { text: "Você pode acabar com uma profissão. Qual?" },
  { text: "Você pode inventar uma nova profissão. Qual?" },
  { text: "Você pode eliminar uma rede social. Qual?" },
  { text: "Você pode tornar algo ilegal só por birra. O quê?" },
  { text: "Você pode trocar dois países de lugar. Quais?" },
  { text: "Você pode escolher um apocalipse. Qual?" },
  { text: "Você pode escolher quem sobrevive. Quem?" },
  { text: "Você pode resetar o mundo. Você faria?" },
  { text: "Você pode alterar a história. O quê?" },
  { text: "Você pode mudar uma invenção. Qual?" },
  { text: "Você pode apagar uma celebridade. Quem?" },
  { text: "Você pode mudar o clima do planeta. Como?" },
  { text: "Mentir para se dar bem é aceitável?" },
  { text: "Roubar de rico é errado?" },
  { text: "Trair amizade é pior que trair namoro?" },
  { text: "Você se venderia por dinheiro?" },
  { text: "Até onde você iria por dinheiro?" },
  { text: "Você denunciaria um amigo?" },
  { text: "Perdoaria uma traição?" },
  { text: "Mentiria para proteger alguém?" },
  { text: "Faria algo errado se ninguém descobrisse?" },
  { text: "Você acredita em karma?" },
  { text: "Dinheiro compra felicidade?" },
  { text: "Você prefere ser temido ou respeitado?" },
  { text: "Vale tudo para vencer?" },
  { text: "Você confiaria em si mesmo?" },
  { text: "Você acorda invisível. O que faz primeiro?" },
  { text: "Você troca de corpo com alguém do grupo. Quem?" },
  { text: "Você acorda famoso. O que faz?" },
  { text: "Você acorda milionário. Qual sua primeira compra?" },
  { text: "Você acorda um ano no passado. O que faria?" },
  { text: "Você acorda um ano no futuro. O que faria?" },
  { text: "Você pode ler a mente de uma pessoa por um dia. Quem seria essa pessoa?" },
  { text: "Você pode voltar no tempo uma vez. Para quando?" },
  { text: "Você pode congelar alguém por uma hora. Quem?" },
  { text: "Você pode silenciar alguém por um dia. Quem?" },
  { text: "Você pode expulsar alguém da Terra. Quem?" },
  { text: "Você pode escolher uma habilidade inútil. Qual?" },
  { text: "Você pode escolher um superpoder ruim. Qual?" },
  { text: "Você pode trocar de vida com alguém famoso. Quem?" },
  { text: "Você pode viver sem internet. Quanto tempo?" },
  { text: "Você pode apagar uma memória sua. Qual?" },
  { text: "Você pode ver o futuro. O que vai querer saber?" },
  { text: "Você pode mudar seu nome. Para qual?" },
  { text: "Preferiria ser rico e odiado ou pobre e amado?" },
  { text: "Preferiria saber como vai morrer ou quando?" },
  { text: "Preferiria perder dinheiro ou amigos?" },
  { text: "Preferiria ser famoso ou anônimo?" },
  { text: "Preferiria morar fora ou nunca sair do país?" },
  { text: "Preferiria viver 100 anos sem grandes emoções ou 40 anos intensos?" },
  { text: "Preferiria sempre falar a verdade ou sempre mentir?" },
  { text: "Preferiria nunca mais mentir ou nunca mais ouvir mentiras?" },
  { text: "Preferiria ser muito bonito ou muito inteligente?" },
  { text: "Preferiria ser sortudo ou esforçado?" },
  { text: "Preferiria silêncio eterno ou barulho constante?" },
  { text: "Preferiria não sentir dor ou não sentir medo?" },
  { text: "Preferiria ser esquecido ou lembrado negativamente?" },
  { text: "Preferiria errar em público ou sozinho?" },
  { text: "Preferiria perder memória ou emoções?" },
  { text: "Preferiria controlar o tempo ou as pessoas?" },
  { text: "Preferiria viver sem amor ou sem ambição?" },
  { text: "Qual famoso você ficaria?" },
  { text: "Qual famoso você não suportaria conviver?" },
  { text: "Qual famoso parece chato pessoalmente?" },
  { text: "Quem é superestimado?" },
  { text: "Quem é subestimado?" },
  { text: "Qual profissão você não teria?" },
  { text: "Qual profissão parece golpe?" },
  { text: "Qual profissão é injustiçada?" },
  { text: "Quem você acha que mente muito?" },
  { text: "Quem parece gente boa mas não é?" },
  { text: "Quem parece chato mas deve ser legal?" },
  { text: "Em quem você não confiaria?" },
  { text: "Quem você chamaria para um assalto a banco?" },
  { text: "Quem você deixaria de fora de um plano?" },
  { text: "Quem seria um ditador perigoso?" },
  { text: "Quem seria um herói improvável?" },
  { text: "Quem seria cancelado rápido?" },
  { text: "Quem sobreviveria ao apocalipse?" },
  { text: "Quem morreria primeiro?" },
  { text: "Qual foi sua melhor decisão?" },
  { text: "Qual foi sua maior vergonha?" },
  { text: "Algo que ninguém imagina sobre você?" },
  { text: "Algo que você finge gostar?" },
  { text: "Algo que você odeia, mas aceita?" },
  { text: "Algo que você tolera?" },
  { text: "Algo que você não tolera?" },
  { text: "Algo que te faz perder a paciência?" },
  { text: "Algo que te deixa confiante?" },
  { text: "Algo que você esconde?" },
  { text: "Algo que você exagera?" },
  { text: "Algo que você minimiza?" },
  { text: "Algo que você evita?" },
  { text: "Algo que você enfrenta?" },
  { text: "Cite em poucas palavras uma maneira absurda de ficar rico." },
  { text: "O dinheiro muda as pessoas?" },
  { text: "Você prefere ganhar pouco e dormir bem ou ganhar muito e se estressar?" },
  { text: "Você emprestaria dinheiro a amigos?" },
  { text: "Você cobraria um amigo?" },
  { text: "Já perdeu dinheiro por confiança?" },
  { text: "Faria algo ilegal por dinheiro?" },
  { text: "Quanto dinheiro é “suficiente”?" },
  { text: "O que você faria com 1 milhão?" },
  { text: "O que faria com 100 milhões?" },
  { text: "O que não faria nem por dinheiro?" },
  { text: "O que faria por dinheiro fácil?" },
  { text: "Você investe ou gasta?" },
  { text: "Você prefere gastar ou guardar?" },
  { text: "Você prefere luxo ou simplicidade?" },
  { text: "Você prefere estabilidade ou risco?" },
  { text: "Dinheiro traz liberdade?" },
  { text: "Dinheiro traz problemas?" },
  { text: "Quem manda: dinheiro ou poder?" },
  { text: "Você quer ser rico ou influente?" },
  { text: "Algo superestimado?" },
  { text: "Algo subestimado?" },
  { text: "Algo que todo mundo gosta menos você?" },
  { text: "Algo que você gosta mas todo mundo odeia?" },
  { text: "Algo que deveria acabar?" },
  { text: "Algo que deveria voltar?" },
  { text: "Algo que ninguém fala mas pensa?" },
  { text: "Algo que é tabu à toa?" },
  { text: "Algo que virou moda sem sentido?" },
  { text: "Algo que nunca vai fazer sentido?" },
  { text: "Algo que você não entende?" },
  { text: "Algo que você finge entender?" },
  { text: "Algo que você defende?" },
  { text: "Algo que você critica?" },
  { text: "Algo que você ignora?" },
  { text: "Algo que você discorda da maioria?" },
  { text: "Algo que você concorda com a maioria?" },
  { text: "Algo que você mudou de ideia?" },
  { text: "Algo que você nunca mudaria?" },
  { text: "Algo que você acha exagerado?" },
  { text: "Conte uma opinião polêmica" },
  { text: "Conte uma ideia ruim que você teria" },
  { text: "Conte algo que você faria se fosse imortal" },
  { text: "Conte algo que faria se fosse invisível" },
  { text: "Conte algo que faria se fosse rico" },
  { text: "Conte algo que faria se fosse famoso" },
  { text: "Conte algo que faria se não houvesse leis" },
  { text: "Conte algo que você faria diferente hoje" },
  { text: "Conte algo que você faria só uma vez" },
  { text: "Conte algo que você nunca faria" },
  { text: "Conte algo que te dá vergonha" },
  { text: "Conte algo que te dá orgulho" },
  { text: "Conte algo que te diverte" },
  { text: "Conte algo que te incomoda" },
  { text: "Conte algo que você acha injusto" },
  { text: "Conte algo que você acha engraçado" },
  { text: "Conte algo que você acha absurdo" },
  { text: "Conte algo que você acha genial" },
  { text: "Conte algo que você acha inútil" },
  { text: "Conte algo que você acha necessário" },
  { text: "O que você mudaria no passado do mundo?" },
  { text: "Como gostaria de morrer?" },
  { text: "O mundo está melhor ou pior?" },
  { text: "O futuro te anima ou assusta?" },
  { text: "Você acredita em colapso social?" },
  { text: "A tecnologia ajuda ou atrapalha?" },
  { text: "A humanidade tem salvação?" },
  { text: "O ser humano merece o planeta?" },
  { text: "O que vai acabar primeiro?" },
  { text: "O que vai dominar o mundo?" },
  { text: "O que vai ser proibido no futuro?" },
  { text: "O que vai virar luxo?" },
  { text: "O que vai virar lixo?" },
  { text: "O que vai desaparecer?" },
  { text: "O que vai surgir?" },
  { text: "O que vai causar conflitos?" },
  { text: "O que vai unir as pessoas?" },
  { text: "O que vai separar ainda mais?" },
  { text: "O que vai virar piada?" },
  { text: "O que vai virar regra?" },
  { text: "O que vai virar crime?" },
  { text: "Qual lugar não gostaria de ter nascido?" },
  { text: "Qual lugar você nunca pisaria?" },
  { text: "Qual lugar você moraria fácil?" },
  { text: "Qual lugar você acha superestimado?" },
  { text: "Qual lugar você acha subestimado?" },
  { text: "Qual país parece uma cilada?" },
  { text: "Qual país parece interessante?" },
  { text: "Qual cultura você gostaria de viver?" },
  { text: "Qual cultura você não se adaptaria?" },
  { text: "Qual idioma gostaria de falar?" },
  { text: "Qual idioma parece inútil?" },
  { text: "Qual tradição você aboliria?" },
  { text: "Qual tradição você manteria?" },
  { text: "Qual regra social é falsa?" },
  { text: "Qual regra social é necessária?" },
  { text: "Qual mentira é aceitável?" },
  { text: "Qual verdade dói mais?" },
  { text: "Qual verdade você evita?" },
  { text: "Qual mentira você conta?" },
  { text: "Qual mentira você já contou?" },
  { text: "Qual decisão foi por impulso?" },
  { text: "Qual decisão foi por medo?" },
  { text: "Qual decisão foi por pressão?" },
  { text: "Qual decisão foi por vontade?" },
  { text: "Qual erro você repetiria?" },
  { text: "Qual erro você evitaria?" },
  { text: "Qual risco você correria?" },
  { text: "Qual risco você evitaria?" },
  { text: "Qual escolha te define?" },
  { text: "Qual escolha te limita?" },
  { text: "Qual escolha te libertou?" },
  { text: "Qual escolha te ferrou?" },
  { text: "Qual hábito você manteria?" },
  { text: "Qual hábito você largaria?" },
  { text: "Qual hábito te prejudica?" },
  { text: "Qual hábito te ajuda?" },
  { text: "Qual regra você quebraria?" },
  { text: "Qual regra você seguiria?" },
  { text: "Qual conselho você ignorou?" },
  { text: "Qual conselho você deveria ter seguido?" },
  { text: "Qual pergunta você gosta?" },
  { text: "Qual pergunta gera debate?" },
  { text: "Qual pergunta gera briga?" },
  { text: "Qual pergunta gera riso?" },
  { text: "Qual pergunta gera verdade?" }
];

export default galera;