const galera = [
  "Você pode cometer um crime sem ser condenado. Qual seria?",
  "Você pode apagar um país do mapa. Qual?",
  "Você pode destruir um lugar no mundo. Qual?",
  "Você pode mudar uma lei absurda. Qual?",
  "Você pode criar uma lei inútil. Qual?",
  "Você pode proibir algo comum. O quê?",
  "Você pode obrigar todo mundo a fazer algo estranho. O quê?",
  "Você pode escolher uma regra para a humanidade. Qual?",
  "Você pode acabar com uma profissão. Qual?",
  "Você pode inventar uma nova profissão. Qual?",
  "Você pode eliminar uma rede social. Qual?",
  "Você pode tornar algo ilegal só por birra. O quê?",
  "Você pode trocar dois países de lugar. Quais?",
  "Você pode escolher um apocalipse. Qual?",
  "Você pode escolher quem sobrevive. Quem?",
  "Você pode resetar o mundo. Você faria?",
  "Você pode alterar a história. O quê?",
  "Você pode mudar uma invenção. Qual?",
  "Você pode apagar uma celebridade. Quem?",
  "Você pode mudar o clima do planeta. Como?",
  "Mentir para se dar bem é aceitável?",
  "Roubar de rico é errado?",
  "Trair amizade é pior que trair namoro?",
  "Você se venderia por dinheiro?",
  "Até quanto você iria por dinheiro?",
  "Você denunciaria um amigo?",
  "Perdoaria uma traição?",
  "Mentiria para proteger alguém?",
  "Faria algo errado se ninguém descobrisse?",
  "Você acredita em karma?",
  "Todo mundo tem um preço?",
  "Poder vale mais que dinheiro?",
  "Dinheiro compra felicidade?",
  "Justiça é realmente justa?",
  "Você prefere ser temido ou respeitado?",
  "Vale tudo para vencer?",
  "Você pisaria em alguém para subir?",
  "Lealdade tem limite?",
  "Você se considera uma boa pessoa?",
  "Você confiaria em você mesmo?",
  "Você acorda invisível. O que faz primeiro?",
  "Você troca de corpo com alguém do grupo. Quem?",
  "Você acorda famoso. O que faz?",
  "Você acorda milionário. O que muda?",
  "Você acorda no passado. Para onde vai?",
  "Você acorda no futuro. Quanto tempo?",
  "Você pode ler mentes por um dia. Usaria?",
  "Você pode voltar no tempo uma vez. Para quando?",
  "Você pode congelar alguém por 1 hora. Quem?",
  "Você pode silenciar alguém por um dia. Quem?",
  "Você pode expulsar alguém da Terra. Quem?",
  "Você pode escolher uma habilidade inútil. Qual?",
  "Você pode escolher um superpoder ruim. Qual?",
  "Você pode trocar de vida com alguém famoso. Quem?",
  "Você pode viver sem internet. Quanto tempo?",
  "Você pode viver sem dinheiro. Aceita?",
  "Você pode apagar uma memória sua. Qual?",
  "Você pode ver o futuro. Quer?",
  "Você pode esquecer alguém. Quem?",
  "Você pode mudar seu nome. Para qual?",
  "Preferiria ser rico e odiado ou pobre e amado?",
  "Preferiria nunca mais trabalhar ou nunca mais viajar?",
  "Preferiria saber como vai morrer ou quando?",
  "Preferiria perder dinheiro ou amigos?",
  "Preferiria ser famoso ou anônimo?",
  "Preferiria morar fora ou nunca sair do país?",
  "Preferiria viver 100 anos ou 40 intensos?",
  "Preferiria sempre falar a verdade ou sempre mentir?",
  "Preferiria nunca mais mentir ou nunca mais ouvir mentiras?",
  "Preferiria ser muito bonito ou muito inteligente?",
  "Preferiria ser sortudo ou esforçado?",
  "Preferiria ser líder ou mandado?",
  "Preferiria silêncio eterno ou barulho constante?",
  "Preferiria não sentir dor ou não sentir medo?",
  "Preferiria ser esquecido ou lembrado negativamente?",
  "Preferiria errar em público ou sozinho?",
  "Preferiria saber tudo ou sentir tudo?",
  "Preferiria perder memória ou emoções?",
  "Preferiria controlar o tempo ou as pessoas?",
  "Preferiria viver sem amor ou sem ambição?",
  "Qual famoso você ficaria?",
  "Qual famoso você não suportaria conviver?",
  "Qual famoso parece chato pessoalmente?",
  "Quem é superestimado?",
  "Quem é subestimado?",
  "Qual profissão você não teria?",
  "Qual profissão parece golpe?",
  "Qual profissão é injustiçada?",
  "Quem você acha que mente muito?",
  "Quem parece gente boa mas não é?",
  "Quem parece chato mas deve ser legal?",
  "Quem você não confiaria?",
  "Quem você chamaria para um golpe?",
  "Quem você deixaria de fora de um plano?",
  "Quem seria um péssimo líder?",
  "Quem seria um ditador perigoso?",
  "Quem seria um herói improvável?",
  "Quem seria cancelado rápido?",
  "Quem sobreviveria ao apocalipse?",
  "Quem morreria primeiro?",
  "Qual foi sua pior decisão?",
  "Qual foi sua melhor decisão?",
  "Qual foi sua maior vergonha?",
  "Algo que você se arrepende?",
  "Algo que faria diferente?",
  "Algo que ninguém imagina sobre você?",
  "Algo que você finge gostar?",
  "Algo que você odeia mas aceita?",
  "Algo que você tolera?",
  "Algo que você não tolera?",
  "Algo que te irrita facilmente?",
  "Algo que te faz perder a paciência?",
  "Algo que te deixa desconfortável?",
  "Algo que te deixa confiante?",
  "Algo que te deixa inseguro?",
  "Algo que você esconde?",
  "Algo que você exagera?",
  "Algo que você minimiza?",
  "Algo que você evita?",
  "Algo que você enfrenta?",
  "Cite em poucas palavras uma maneira absurda de ficar rico.",
  "O dinheiro muda as pessoas?",
  "Você prefere ganhar pouco e dormir bem ou ganhar muito e se estressar?",
  "Você emprestaria dinheiro a amigos?",
  "Você cobraria um amigo?",
  "Já perdeu dinheiro por confiança?",
  "Faria algo ilegal por dinheiro?",
  "Quanto dinheiro é “suficiente”?",
  "O que você faria com 1 milhão?",
  "O que faria com 100 milhões?",
  "O que não faria nem por dinheiro?",
  "O que faria por dinheiro fácil?",
  "Você investe ou gasta?",
  "Você prefere gastar ou guardar?",
  "Você prefere luxo ou simplicidade?",
  "Você prefere estabilidade ou risco?",
  "Dinheiro traz liberdade?",
  "Dinheiro traz problemas?",
  "Quem manda: dinheiro ou poder?",
  "Você quer ser rico ou influente?",
  "Algo superestimado?",
  "Algo subestimado?",
  "Algo que todo mundo gosta menos você?",
  "Algo que você gosta mas todo mundo odeia?",
  "Algo que deveria acabar?",
  "Algo que deveria voltar?",
  "Algo que ninguém fala mas pensa?",
  "Algo que é tabu à toa?",
  "Algo que virou moda sem sentido?",
  "Algo que nunca vai fazer sentido?",
  "Algo que você não entende?",
  "Algo que você finge entender?",
  "Algo que você defende?",
  "Algo que você critica?",
  "Algo que você ignora?",
  "Algo que você discorda da maioria?",
  "Algo que você concorda com a maioria?",
  "Algo que você mudou de ideia?",
  "Algo que você nunca mudaria?",
  "Algo que você acha exagerado?",
  "Conte uma opinião polêmica",
  "Conte uma ideia ruim que você teria",
  "Conte algo que você faria se fosse imortal",
  "Conte algo que faria se fosse invisível",
  "Conte algo que faria se fosse rico",
  "Conte algo que faria se fosse famoso",
  "Conte algo que faria se não houvesse leis",
  "Conte algo que você faria diferente hoje",
  "Conte algo que você faria só uma vez",
  "Conte algo que você nunca faria",
  "Conte algo que te dá vergonha",
  "Conte algo que te dá orgulho",
  "Conte algo que te diverte",
  "Conte algo que te incomoda",
  "Conte algo que você acha injusto",
  "Conte algo que você acha engraçado",
  "Conte algo que você acha absurdo",
  "Conte algo que você acha genial",
  "Conte algo que você acha inútil",
  "Conte algo que você acha necessário",
  "Mundo e futuro",
  "Como gostaria de morrer?",
  "O mundo está melhor ou pior?",
  "O futuro te anima ou assusta?",
  "Você acredita em colapso social?",
  "A tecnologia ajuda ou atrapalha?",
  "A humanidade tem salvação?",
  "O ser humano merece o planeta?",
  "O que vai acabar primeiro?",
  "O que vai dominar o mundo?",
  "O que vai ser proibido no futuro?",
  "O que vai virar luxo?",
  "O que vai virar lixo?",
  "O que vai desaparecer?",
  "O que vai surgir?",
  "O que vai causar conflitos?",
  "O que vai unir as pessoas?",
  "O que vai separar ainda mais?",
  "O que vai virar piada?",
  "O que vai virar regra?",
  "O que vai virar crime?",
  "Qual lugar não gostaria de ter nascido?",
  "Qual lugar você nunca pisaria?",
  "Qual lugar você moraria fácil?",
  "Qual lugar você acha superestimado?",
  "Qual lugar você acha subestimado?",
  "Qual país parece uma cilada?",
  "Qual país parece interessante?",
  "Qual cultura você gostaria de viver?",
  "Qual cultura você não se adaptaria?",
  "Qual idioma gostaria de falar?",
  "Qual idioma parece inútil?",
  "Qual tradição você aboliria?",
  "Qual tradição você manteria?",
  "Qual regra social é falsa?",
  "Qual regra social é necessária?",
  "Qual mentira é aceitável?",
  "Qual verdade dói mais?",
  "Qual verdade você evita?",
  "Qual mentira você conta?",
  "Qual mentira você já contou?",
  "Qual decisão foi por impulso?",
  "Qual decisão foi por medo?",
  "Qual decisão foi por pressão?",
  "Qual decisão foi por vontade?",
  "Qual erro você repetiria?",
  "Qual erro você evitaria?",
  "Qual risco você correria?",
  "Qual risco você evitaria?",
  "Qual escolha te define?",
  "Qual escolha te limita?",
  "Qual escolha te libertou?",
  "Qual escolha te ferrou?",
  "Qual hábito você manteria?",
  "Qual hábito você largaria?",
  "Qual hábito te prejudica?",
  "Qual hábito te ajuda?",
  "Qual regra você quebraria?",
  "Qual regra você seguiria?",
  "Qual conselho você ignorou?",
  "Qual conselho você deveria ter seguido?",
  "Qual pergunta você evita?",
  "Qual pergunta você gosta?",
  "Qual pergunta te incomoda?",
  "Qual pergunta te define?",
  "Qual pergunta gera caos?",
  "Qual pergunta gera silêncio?",
  "Qual pergunta gera debate?",
  "Qual pergunta gera briga?",
  "Qual pergunta gera riso?",
  "Qual pergunta gera verdade?"
];

export default galera;