const mimica = [
  // Magia e feitiços
  { category: "Magia e feitiços", text: "Mago errou feitiço" },
  { category: "Magia e feitiços", text: "Bruxa perdeu a vassoura" },
  { category: "Magia e feitiços", text: "Feitiço para virar galinha" },
  { category: "Magia e feitiços", text: "Varinha não funciona" },
  { category: "Magia e feitiços", text: "Bruxo explodiu caldeirão" },
  { category: "Magia e feitiços", text: "Poção deu errado" },
  { category: "Magia e feitiços", text: "Mago virou sapo" },
  { category: "Magia e feitiços", text: "Bruxa confundiu encantamento" },
  { category: "Magia e feitiços", text: "Feitiço grudou mãos" },
  { category: "Magia e feitiços", text: "Varinha com defeito" },
  { category: "Magia e feitiços", text: "Magia saiu torta" },
  { category: "Magia e feitiços", text: "Bruxo sem poderes" },
  { category: "Magia e feitiços", text: "Mago soltando faísca" },
  { category: "Magia e feitiços", text: "Poção virou sorvete" },
  { category: "Magia e feitiços", text: "Bruxa errou palavra" },
  { category: "Magia e feitiços", text: "Mago perdeu chapéu" },
  { category: "Magia e feitiços", text: "Magia fora controle" },

  // Criaturas mitológicas
  { category: "Criaturas mitológicas", text: "Dragão com soluço" },
  { category: "Criaturas mitológicas", text: "Centauro escorregando na lama" },
  { category: "Criaturas mitológicas", text: "Minotauro perdido no shopping" },
  { category: "Criaturas mitológicas", text: "Sereia fora d’água" },
  { category: "Criaturas mitológicas", text: "Kraken preso na garrafa" },
  { category: "Criaturas mitológicas", text: "Ciclopes procurando óculos" },
  { category: "Criaturas mitológicas", text: "Dragão cuspindo bolhas" },
  { category: "Criaturas mitológicas", text: "Vampiro queimou o dedo" },
  { category: "Criaturas mitológicas", text: "Medusa penteando cobras" },
  { category: "Criaturas mitológicas", text: "Unicórnio quebrando chifre" },
  { category: "Criaturas mitológicas", text: "Dragão gripado" },
  { category: "Criaturas mitológicas", text: "Sereia usando celular" },

  // Mundos imaginários
  { category: "Mundos imaginários", text: "Planeta feito de doces" },
  { category: "Mundos imaginários", text: "Planeta de gelatina" },
  { category: "Mundos imaginários", text: "Mundo sem gravidade" },
  { category: "Mundos imaginários", text: "Ilha andando sozinha" },
  { category: "Mundos imaginários", text: "Floresta falante de fofoca" },
  { category: "Mundos imaginários", text: "Montanhas dançando samba" },
  { category: "Mundos imaginários", text: "Cidade dentro da nuvem" },
  { category: "Mundos imaginários", text: "Estrada infinita circular" },
  { category: "Mundos imaginários", text: "Céu caindo" },
  { category: "Mundos imaginários", text: "Planeta cheio de espelhos" },
  { category: "Mundos imaginários", text: "Reino governado por gatos" },
  { category: "Mundos imaginários", text: "Mundo feito de papel" },
  { category: "Mundos imaginários", text: "Ilha que respira" },

  // Profissões malucas
  { category: "Profissões malucas", text: "Dentista de tubarão" },
  { category: "Profissões malucas", text: "Cozinheiro de pedras" },
  { category: "Profissões malucas", text: "Professor de fantasmas" },
  { category: "Profissões malucas", text: "Psicólogo de robôs" },
  { category: "Profissões malucas", text: "Babá de dragões" },
  { category: "Profissões malucas", text: "Personal trainer de preguiças" },
  { category: "Profissões malucas", text: "Astrólogo corporativo sério" },
  { category: "Profissões malucas", text: "Estilista de monstros" },
  { category: "Profissões malucas", text: "Médico de zumbis" },
  { category: "Profissões malucas", text: "DJ de igreja" },
  { category: "Profissões malucas", text: "Fotógrafo de espíritos" },
  { category: "Profissões malucas", text: "Engenheiro de castelos" },
  { category: "Profissões malucas", text: "Advogado de piratas" },
  { category: "Profissões malucas", text: "Treinador de nuvens" },
  { category: "Profissões malucas", text: "Jardineiro de cactos" },
  { category: "Profissões malucas", text: "Maestro de galinhas" },
  { category: "Profissões malucas", text: "Técnico de varinhas" },
  { category: "Profissões malucas", text: "Ator de sombras" },

  // Animais inusitados
  { category: "Animais inusitados", text: "Cachorro dirigindo carro" },
  { category: "Animais inusitados", text: "Gato fazendo yoga" },
  { category: "Animais inusitados", text: "Macaco usando terno" },
  { category: "Animais inusitados", text: "Vaca dançando balé" },
  { category: "Animais inusitados", text: "Pinguim surfando na onda" },
  { category: "Animais inusitados", text: "Cavalo jogando xadrez" },
  { category: "Animais inusitados", text: "Galinha atravessando rua" },
  { category: "Animais inusitados", text: "Porco andando skate" },
  { category: "Animais inusitados", text: "Elefante pintando quadro" },
  { category: "Animais inusitados", text: "Papagaio dando sermão" },
  { category: "Animais inusitados", text: "Coelho fazendo mágica" },
  { category: "Animais inusitados", text: "Cobra tocando violão" },
  { category: "Animais inusitados", text: "Urso fazendo compras" },
  { category: "Animais inusitados", text: "Peixe andando bicicleta" },
  { category: "Animais inusitados", text: "Gato roubando comida" },
  { category: "Animais inusitados", text: "Cachorro usando óculos" },
  { category: "Animais inusitados", text: "Macaco tirando selfie" },
  { category: "Animais inusitados", text: "Pato usando chapéu" },
  { category: "Animais inusitados", text: "Cavalo no escritório" },
  { category: "Animais inusitados", text: "Gato programando código" },

  // Alienígenas
  { category: "Alienígenas", text: "Alien confundiu banheiro" },
  { category: "Alienígenas", text: "ET pedindo pizza" },
  { category: "Alienígenas", text: "Alien estudando humanos" },
  { category: "Alienígenas", text: "Disco voador estacionando" },
  { category: "Alienígenas", text: "ET fazendo turismo" },
  { category: "Alienígenas", text: "Alien usando celular" },
  { category: "Alienígenas", text: "ET dançando forró" },
  { category: "Alienígenas", text: "Alien atrasado na invasão" },
  { category: "Alienígenas", text: "Marciano tirando foto" },
  { category: "Alienígenas", text: "ET fazendo mímica" },

  // Heróis improváveis
  { category: "Heróis improváveis", text: "Herói muito azarado" },
  { category: "Heróis improváveis", text: "Velhinha salvando cidade" },
  { category: "Heróis improváveis", text: "Bebê com capa" },
  { category: "Heróis improváveis", text: "Porteiro salvando o mundo" },
  { category: "Heróis improváveis", text: "Faxineiro super herói" },
  { category: "Heróis improváveis", text: "Herói com medo" },
  { category: "Heróis improváveis", text: "Herói perdeu os poderes" },
  { category: "Heróis improváveis", text: "Tiozão justiceiro urbano" },
  { category: "Heróis improváveis", text: "Avó lutando contra o crime" },
  { category: "Heróis improváveis", text: "Herói atrasado na batalha" },
  { category: "Heróis improváveis", text: "Heroína com sono" },
  { category: "Heróis improváveis", text: "Herói esqueceu identidade" },
  { category: "Heróis improváveis", text: "Herói fora de forma" },
  { category: "Heróis improváveis", text: "Herói salvando o gato" },
  { category: "Heróis improváveis", text: "Herói errando a pose" },

  // Superpoderes estranhos
  { category: "Superpoderes estranhos", text: "Poder de espirrar" },
  { category: "Superpoderes estranhos", text: "Invisibilidade só aos domingos" },
  { category: "Superpoderes estranhos", text: "Voar muito baixo" },
  { category: "Superpoderes estranhos", text: "Teleporte errado" },
  { category: "Superpoderes estranhos", text: "Super força frágil" },
  { category: "Superpoderes estranhos", text: "Falar com paredes" },
  { category: "Superpoderes estranhos", text: "Controlar fila do banco" },
  { category: "Superpoderes estranhos", text: "Parar tempo espirrando" },
  { category: "Superpoderes estranhos", text: "Transformar água em sopa" },
  { category: "Superpoderes estranhos", text: "Magnetismo de talheres" },
  { category: "Superpoderes estranhos", text: "Voltar no tempo" },

  // Cenas famosas
  { category: "Cenas famosas de filmes", text: "Titanic afundando navio" },
  { category: "Cenas famosas de filmes", text: "Matrix desviando balas" },
  { category: "Cenas famosas de filmes", text: "Rocky subindo escadas" },
  { category: "Cenas famosas de filmes", text: "Jurassic Park correndo" },
  { category: "Cenas famosas de filmes", text: "Star Wars duelo" },
  { category: "Cenas famosas de filmes", text: "Homem Aranha balançando" },
  { category: "Cenas famosas de filmes", text: "ET telefonando casa" },
  { category: "Cenas famosas de filmes", text: "Vingadores reunidos épico" },
  { category: "Cenas famosas de filmes", text: "Simba no penhasco" },
  { category: "Cenas famosas de filmes", text: "Senhor Anéis anel" },
  { category: "Cenas famosas de filmes", text: "Batman na sombra" },
  { category: "Cenas famosas de filmes", text: "Coringa rindo louco" },
  { category: "Cenas famosas de filmes", text: "Indiana Jones fugindo" },
  { category: "Cenas famosas de filmes", text: "Tubarão aparecendo água" },
  { category: "Cenas famosas de filmes", text: "Harry Potter varinha" },
  { category: "Cenas famosas de filmes", text: "Homem Ferro pousando" },
  { category: "Cenas famosas de filmes", text: "Frozen soltando magia" },
  { category: "Cenas famosas de filmes", text: "Pantera Negra saudação" },
  { category: "Cenas famosas de filmes", text: "Avatar montando criatura" },
  { category: "Cenas famosas de filmes", text: "Toy Story brinquedos vivos" },

  // Combinações
  { category: "Profissão e lazer", text: "Médico na praia" },
  { category: "Humor e trabalho", text: "Palhaço sério na reunião" },
  { category: "Religião e esporte", text: "Padre surfando" },
  { category: "Educação e música", text: "Professor dançando" },
  { category: "Pirataria e trabalho", text: "Pirata no escritório" },
  { category: "Artes marciais e cotidiano", text: "Ninja fazendo compras" },
  { category: "Autoridade e arte", text: "Policial cantando" },
  { category: "Cozinha e espaço", text: "Cozinheiro no espaço" },
  { category: "Sobrenatural e cotidiano", text: "Vampiro no sol" },
  { category: "Terror e bem-estar", text: "Zumbi na academia" },
  { category: "Magia e transporte", text: "Bruxa usando Uber" },
  { category: "Tecnologia e bem-estar", text: "Robô fazendo yoga" },
  { category: "Velho oeste e cidade", text: "Cowboy no ônibus" },
  { category: "Alienígenas e sociedade", text: "Alien no churrasco" },
  { category: "Criaturas fantásticas e cidade", text: "Dragão no elevador" },
  { category: "Criaturas mitológicas e tecnologia", text: "Cavaleiro usando celular" },
  { category: "Magia e burocracia", text: "Mago pagando boleto" }
];

export default mimica;
