const mimica: string[] = [
  // Magia e feitiços
  "Categoria: Magia e feitiços\n\nMago errou feitiço",
  "Categoria: Magia e feitiços\n\nBruxa perdeu a vassoura",
  "Categoria: Magia e feitiços\n\nFeitiço para virar galinha",
  "Categoria: Magia e feitiços\n\nVarinha não funciona",
  "Categoria: Magia e feitiços\n\nBruxo explodiu caldeirão",
  "Categoria: Magia e feitiços\n\nPoção deu errado",
  "Categoria: Magia e feitiços\n\nMago virou sapo",
  "Categoria: Magia e feitiços\n\nBruxa confundiu encantamento",
  "Categoria: Magia e feitiços\n\nFeitiço grudou mãos",
  "Categoria: Magia e feitiços\n\nVarinha com defeito",
  "Categoria: Magia e feitiços\n\nMagia saiu torta",
  "Categoria: Magia e feitiços\n\nBruxo sem poderes",
  "Categoria: Magia e feitiços\n\nMago soltando faísca",
  "Categoria: Magia e feitiços\n\nPoção virou sorvete",
  "Categoria: Magia e feitiços\n\nBruxa errou palavra",
  "Categoria: Magia e feitiços\n\nMago perdeu chapéu",
  "Categoria: Magia e feitiços\n\nMagia fora controle",

  // Criaturas mitológicas
  "Categoria: Criaturas mitológicas\n\nDragão com soluço",
  "Categoria: Criaturas mitológicas\n\nCentauro escorregando na lama",
  "Categoria: Criaturas mitológicas\n\nMinotauro perdido no shopping",
  "Categoria: Criaturas mitológicas\n\nSereia fora d’água",
  "Categoria: Criaturas mitológicas\n\nKraken preso na garrafa",
  "Categoria: Criaturas mitológicas\n\nCiclopes procurando óculos",
  "Categoria: Criaturas mitológicas\n\nDragão cuspindo bolhas",
  "Categoria: Criaturas mitológicas\n\nVampiro queimou o dedo",
  "Categoria: Criaturas mitológicas\n\nMedusa penteando cobras",
  "Categoria: Criaturas mitológicas\n\nUnicórnio quebrando chifre",
  "Categoria: Criaturas mitológicas\n\nDragão gripado",
  "Categoria: Criaturas mitológicas\n\nSereia usando celular",

  // Mundos imaginários
  "Categoria: Mundos imaginários\n\nPlaneta feito de doces",
  "Categoria: Mundos imaginários\n\nPlaneta de gelatina",
  "Categoria: Mundos imaginários\n\nMundo sem gravidade",
  "Categoria: Mundos imaginários\n\nIlha andando sozinha",
  "Categoria: Mundos imaginários\n\nFloresta falante de fofoca",
  "Categoria: Mundos imaginários\n\nMontanhas dançando samba",
  "Categoria: Mundos imaginários\n\nMundo invertido estranho",
  "Categoria: Mundos imaginários\n\nCidade dentro da nuvem",
  "Categoria: Mundos imaginários\n\nEstrada infinita circular",
  "Categoria: Mundos imaginários\n\nCéu caindo",
  "Categoria: Mundos imaginários\n\nPlaneta cheio de espelhos",
  "Categoria: Mundos imaginários\n\nReino governado por gatos",
  "Categoria: Mundos imaginários\n\nMundo feito de papel",
  "Categoria: Mundos imaginários\n\nIlha que respira",

  // Profissões malucas
  "Categoria: Profissões malucas\n\nDentista de tubarão",
  "Categoria: Profissões malucas\n\nCozinheiro de pedras",
  "Categoria: Profissões malucas\n\nProfessor de fantasmas",
  "Categoria: Profissões malucas\n\nPsicólogo de robôs",
  "Categoria: Profissões malucas\n\nBabá de dragões",
  "Categoria: Profissões malucas\n\nPersonal trainer de preguiças",
  "Categoria: Profissões malucas\n\nAstrólogo corporativo sério",
  "Categoria: Profissões malucas\n\nEstilista de monstros",
  "Categoria: Profissões malucas\n\nMédico de zumbis",
  "Categoria: Profissões malucas\n\nDJ de igreja",
  "Categoria: Profissões malucas\n\nFotógrafo de espíritos",
  "Categoria: Profissões malucas\n\nEngenheiro de castelos",
  "Categoria: Profissões malucas\n\nAdvogado de piratas",
  "Categoria: Profissões malucas\n\nTreinador de nuvens",
  "Categoria: Profissões malucas\n\nJardineiro de cactos",
  "Categoria: Profissões malucas\n\nMaestro de galinhas",
  "Categoria: Profissões malucas\n\nTécnico de varinhas",
  "Categoria: Profissões malucas\n\nAtor de sombras",

  // Animais fazendo algo inusitado
  "Categoria: Animais inusitados\n\nCachorro dirigindo carro",
  "Categoria: Animais inusitados\n\nGato fazendo yoga",
  "Categoria: Animais inusitados\n\nMacaco usando terno",
  "Categoria: Animais inusitados\n\nVaca dançando balé",
  "Categoria: Animais inusitados\n\nPinguim surfando na onda",
  "Categoria: Animais inusitados\n\nCavalo jogando xadrez",
  "Categoria: Animais inusitados\n\nGalinha atravessando rua",
  "Categoria: Animais inusitados\n\nPorco andando skate",
  "Categoria: Animais inusitados\n\nElefante pintando quadro",
  "Categoria: Animais inusitados\n\nPapagaio dando sermão",
  "Categoria: Animais inusitados\n\nCoelho fazendo mágica",
  "Categoria: Animais inusitados\n\nCobra tocando violão",
  "Categoria: Animais inusitados\n\nUrso fazendo compras",
  "Categoria: Animais inusitados\n\nPeixe andando bicicleta",
  "Categoria: Animais inusitados\n\nGato roubando comida",
  "Categoria: Animais inusitados\n\nCachorro usando óculos",
  "Categoria: Animais inusitados\n\nMacaco tirando selfie",
  "Categoria: Animais inusitados\n\nPato usando chapéu",
  "Categoria: Animais inusitados\n\nCavalo no escritório",
  "Categoria: Animais inusitados\n\nGato programando código",

  // Alienígenas
  "Categoria: Alienígenas\n\nAlien confundiu banheiro",
  "Categoria: Alienígenas\n\nET pedindo pizza",
  "Categoria: Alienígenas\n\nAlien estudando humanos",
  "Categoria: Alienígenas\n\nDisco voador estacionando",
  "Categoria: Alienígenas\n\nET fazendo turismo",
  "Categoria: Alienígenas\n\nAlien usando celular",
  "Categoria: Alienígenas\n\nET dançando forró",
  "Categoria: Alienígenas\n\nAlien atrasado na invasão",
  "Categoria: Alienígenas\n\nMarciano tirando foto",
  "Categoria: Alienígenas\n\nET fazendo mímica",

  // Heróis improváveis
  "Categoria: Heróis improváveis\n\nHerói muito azarado",
  "Categoria: Heróis improváveis\n\nVelhinha salvando cidade",
  "Categoria: Heróis improváveis\n\nBebê com capa",
  "Categoria: Heróis improváveis\n\nPorteiro salvando o mundo",
  "Categoria: Heróis improváveis\n\nFaxineiro super herói",
  "Categoria: Heróis improváveis\n\nHerói com medo",
  "Categoria: Heróis improváveis\n\nHerói perdeu os poderes",
  "Categoria: Heróis improváveis\n\nTiozão justiceiro urbano",
  "Categoria: Heróis improváveis\n\nAvó lutando contra o crime",
  "Categoria: Heróis improváveis\n\nHerói atrasado na batalha",
  "Categoria: Heróis improváveis\n\nHeroína com sono",
  "Categoria: Heróis improváveis\n\nHerói esqueceu identidade",
  "Categoria: Heróis improváveis\n\nHerói fora de forma",
  "Categoria: Heróis improváveis\n\nHerói salvando o gato",
  "Categoria: Heróis improváveis\n\nHerói errando a pose",

  // Superpoderes estranhos
  "Categoria: Superpoderes estranhos\n\nPoder de espirrar",
  "Categoria: Superpoderes estranhos\n\nInvisibilidade só aos domingos",
  "Categoria: Superpoderes estranhos\n\nVoar muito baixo",
  "Categoria: Superpoderes estranhos\n\nTeleporte errado",
  "Categoria: Superpoderes estranhos\n\nSuper força frágil",
  "Categoria: Superpoderes estranhos\n\nFalar com paredes",
  "Categoria: Superpoderes estranhos\n\nControlar fila do banco",
  "Categoria: Superpoderes estranhos\n\nParar tempo espirrando",
  "Categoria: Superpoderes estranhos\n\nTransformar água em sopa",
  "Categoria: Superpoderes estranhos\n\nMagnetismo de talheres",
  "Categoria: Superpoderes estranhos\n\nVoltar no tempo",

  // Cenas famosas de filmes
  "Categoria: Cenas famosas de filmes\n\nTitanic afundando navio",
  "Categoria: Cenas famosas de filmes\n\nMatrix desviando balas",
  "Categoria: Cenas famosas de filmes\n\nRocky subindo escadas",
  "Categoria: Cenas famosas de filmes\n\nJurassic Park correndo",
  "Categoria: Cenas famosas de filmes\n\nStar Wars duelo",
  "Categoria: Cenas famosas de filmes\n\nHomem Aranha balançando",
  "Categoria: Cenas famosas de filmes\n\nET telefonando casa",
  "Categoria: Cenas famosas de filmes\n\nVingadores reunidos épico",
  "Categoria: Cenas famosas de filmes\n\nSimba no penhasco",
  "Categoria: Cenas famosas de filmes\n\nSenhor Anéis anel",
  "Categoria: Cenas famosas de filmes\n\nBatman na sombra",
  "Categoria: Cenas famosas de filmes\n\nCoringa rindo louco",
  "Categoria: Cenas famosas de filmes\n\nIndiana Jones fugindo",
  "Categoria: Cenas famosas de filmes\n\nTubarão aparecendo água",
  "Categoria: Cenas famosas de filmes\n\nHarry Potter varinha",
  "Categoria: Cenas famosas de filmes\n\nHomem Ferro pousando",
  "Categoria: Cenas famosas de filmes\n\nFrozen soltando magia",
  "Categoria: Cenas famosas de filmes\n\nPantera Negra saudação",
  "Categoria: Cenas famosas de filmes\n\nAvatar montando criatura",
  "Categoria: Cenas famosas de filmes\n\nToy Story brinquedos vivos",

  // Combinações aleatórias
  "Categoria: Combinações aleatórias\n\nMédico na praia",
  "Categoria: Combinações aleatórias\n\nPalhaço sério na reunião",
  "Categoria: Combinações aleatórias\n\nPadre surfando na onda",
  "Categoria: Combinações aleatórias\n\nProfessor dançando funk",
  "Categoria: Combinações aleatórias\n\nPirata no escritório",
  "Categoria: Combinações aleatórias\n\nNinja fazendo compras",
  "Categoria: Combinações aleatórias\n\nPolicial cantando ópera",
  "Categoria: Combinações aleatórias\n\nCozinheiro no espaço",
  "Categoria: Combinações aleatórias\n\nVampiro no sol",
  "Categoria: Combinações aleatórias\n\nZumbi indo à academia",
  "Categoria: Combinações aleatórias\n\nBruxa usando Uber",
  "Categoria: Combinações aleatórias\n\nRobô fazendo yoga",
  "Categoria: Combinações aleatórias\n\nCowboy pegando ônibus",
  "Categoria: Combinações aleatórias\n\nAlien no churrasco",
  "Categoria: Combinações aleatórias\n\nDragão no elevador",
  "Categoria: Combinações aleatórias\n\nCavaleiro usando celular",
  "Categoria: Combinações aleatórias\n\nMago pagando boleto"
];

export default mimica;
