const valeTudo = [
  "Já ficou com alguém do trabalho?",
  "Já mentiu sobre onde estava para sair?",
  "Já foi ou quase foi preso?",
  "Já mandou mensagem para ex bêbado(a)?",
  "Já se humilhou por ex?",
  "Já ficou com mais de uma pessoa no mesmo dia?",
  "Qual foi a maior vergonha da sua vida?",
  "Já stalkeou alguém por mais de 1 hora?",
  "Já beijou alguém que se arrependeu imediatamente?",
  "Já fingiu gostar de alguém só por interesse?",
  "Já terminou por mensagem?",
  "Já levou um fora humilhante?",
  "Já ficou com alguém só pela aparência?",
  "Já ficou com amigo(a) de ex?",
  "Já mentiu idade para pegar alguém?",
  "Já deu PT?",
  "Qual foi o maior mico em público?",
  "Já chorou por alguém que não merecia?",
  "Já fingiu orgasmo?",
  "Já ficou com alguém comprometido(a)?",
  "Já usou alguém para provocar ciúmes?",
  "Já foi rejeitado(a) na hora H?",
  "Já ficou com alguém só por carência?",
  "Já mandou nude para a pessoa errada?",
  "Já recebeu nude inesperado?",
  "Já transou no primeiro encontro?",
  "Já ficou sem lembrar do que fez na noite anterior?",
  "Já teve crush em professor(a)?",
  "Já mentiu sobre experiência sexual?",
  "Já ficou com alguém bem mais velho(a)?",
  "Já ficou com alguém bem mais novo(a)?",
  "Já foi traído(a)?",
  "Já traiu?",
  "Já terminou e se arrependeu?",
  "Já foi o “outro(a)”?",
  "Já beijou alguém só por aposta?",
  "Já ficou com alguém da família de um amigo?",
  "Já foi pego(a) no flagra?",
  "Já fingiu gostar de música só para agradar alguém?",
  "Já chorou depois de beber?",
  "Já se apaixonou por alguém indisponível?",
  "Já fez algo ilegal leve?",
  "Já mentiu para sair escondido(a)?",
  "Já ficou com alguém no banheiro?",
  "Já ficou com alguém em festa da família?",
  "Já se arrependeu logo após transar?",
  "Já ficou com alguém só por status?",
  "Já ignorou alguém de propósito?",
  "Já bloqueou e desbloqueou a mesma pessoa?",
  "Já teve recaída com ex?",
  "Qual sua posição sexual favorita?",
  "Qual parte do corpo você mais gosta?",
  "Qual parte do corpo você menos gosta?",
  "Qual seu maior fetiche leve?",
  "O que mais te excita?",
  "O que mais te broxa?",
  "Prefere dominar ou ser dominado(a)?",
  "Já teve curiosidade por algo diferente?",
  "Luz acesa ou apagada?",
  "Com ou sem som?",
  "Já mentiu sobre tamanho?",
  "Já fingiu experiência?",
  "Já teve medo de desempenho?",
  "Já comparou parceiro(a) com ex?",
  "Já ficou com alguém só pelo beijo?",
  "Já teve vergonha do próprio corpo?",
  "Já transou cansado(a)?",
  "Já transou com raiva?",
  "Já transou por saudade?",
  "Já transou por vingança?",
  "Já ficou com alguém só pela conversa?",
  "Já recusou sexo por preguiça?",
  "Já sentiu ciúmes sem motivo?",
  "Já foi tóxico(a)?",
  "Já perdoou traição?",
  "Já fez algo só para agradar parceiro(a)?",
  "Já mentiu que estava satisfeito(a)?",
  "Já quis algo sério e não foi correspondido?",
  "Já foi muito carente?",
  "Já foi muito frio(a)?",
  "Já se apaixonou rápido demais?",
  "Já perdeu alguém por orgulho?",
  "Já ficou obcecado(a) por alguém?",
  "Já fingiu indiferença?",
  "Já chorou escondido(a)?",
  "Já teve crise de ciúmes?",
  "Já fuçou celular alheio?",
  "Já foi descoberto(a) fuçando?",
  "Já teve relacionamento tóxico?",
  "Já voltou para alguém que te fez mal?",
  "Já fez promessa bêbado(a)?",
  "Já mentiu que esqueceu alguém?",
  "Já fingiu estar bem quando não estava?",
  "Já se comparou com ex do parceiro(a)?",
  "Já teve medo de se apaixonar?",
  "Já evitou sentimento de propósito?",
  "Já se declarou e levou fora?",
  "Já se declarou bêbado(a)?",
  "Já terminou para “ver se sentia falta”?",
  "Já pediu segunda chance?",
  "Verdade ou desafio: mande um emoji para alguém aleatório.",
  "Conte sua maior vergonha sexual (sem detalhes).",
  "Mostre a última conversa arquivada.",
  "Leia a última mensagem que enviou.",
  "Leia a última mensagem que recebeu.",
  "Conte algo que ninguém aqui sabe.",
  "Mostre a última foto da galeria.",
  "Mostre a última música que ouviu.",
  "Fale quem foi seu pior beijo.",
  "Fale quem foi seu melhor beijo.",
  "Fale quem você pegaria aqui.",
  "Fale quem você nunca pegaria aqui.",
  "Fale um defeito seu.",
  "Fale um defeito seu na cama.",
  "Fale uma qualidade sua.",
  "Fale uma qualidade sua na cama.",
  "Imite alguém da roda.",
  "Mande um áudio falando algo constrangedor.",
  "Poste algo aleatório no status.",
  "Troque o fundo do celular por 10 minutos.",
  "Conte uma mentira que já contou.",
  "Conte algo ilegal que já fez (leve).",
  "Conte um segredo antigo.",
  "Conte algo que se arrepende.",
  "Conte algo que faria diferente.",
  "Conte algo que repetiria.",
  "Conte algo que nunca mais faria.",
  "Conte algo que faria hoje.",
  "Conte algo que te dá tesão.",
  "Conte algo que te dá vergonha.",
  "Fale uma fantasia leve.",
  "Fale algo que te deixa inseguro(a).",
  "Fale algo que te deixa confiante.",
  "Fale algo que te deixa com ciúmes.",
  "Fale algo que te faz rir.",
  "Fale algo que te faz chorar.",
  "Fale algo que te irrita fácil.",
  "Fale algo que te conquista rápido.",
  "Fale algo que te afasta.",
  "Fale algo que você esconde.",
  "Mostre o último app aberto.",
  "Mostre o último contato pesquisado.",
  "Mostre a última foto apagada (se tiver).",
  "Leia a última anotação do celular.",
  "Fale quem foi seu maior erro amoroso.",
  "Fale quem foi seu maior acerto amoroso.",
  "Fale quem te marcou mais.",
  "Fale quem você superou.",
  "Fale quem você não superou.",
  "Fale quem você evitaria reencontrar.",
  "Já beijou alguém do mesmo sexo?",
  "Já teve curiosidade?",
  "Já ficou confuso(a) com sentimentos?",
  "Já se sentiu usado(a)?",
  "Já usou alguém?",
  "Já foi dependente emocional?",
  "Já deixou de sair por alguém?",
  "Já deixou de estudar por alguém?",
  "Já deixou de dormir por alguém?",
  "Já deixou de comer por alguém?",
  "Já mudou por alguém?",
  "Já se perdeu por alguém?",
  "Já se encontrou por alguém?",
  "Já se odiou por alguém?",
  "Já se amou mais depois de alguém?",
  "Já sentiu culpa após transar?",
  "Já sentiu vazio após transar?",
  "Já sentiu conexão forte com alguém?",
  "Já sentiu atração só pelo cheiro?",
  "Já sentiu atração só pela voz?",
  "Já sentiu atração só pela atitude?",
  "Já sentiu atração só pela inteligência?",
  "Já se arrependeu de não ter ficado?",
  "Já se arrependeu de ter ficado?",
  "Já foi intenso demais?",
  "Já foi frio demais?",
  "Já foi emocionado(a)?",
  "Já foi desapegado(a)?",
  "Já foi iludido(a)?",
  "Já iludiu alguém?",
  "Já teve medo de compromisso?",
  "Já teve medo de ficar sozinho(a)?",
  "Já quis sumir?",
  "Já quis voltar no tempo?",
  "Já quis recomeçar tudo?",
  "Já sentiu inveja amorosa?",
  "Já sentiu orgulho amoroso?",
  "Já sentiu vergonha amorosa?",
  "Já sentiu raiva amorosa?",
  "Já sentiu tudo ao mesmo tempo?",
  "Já mentiu dizendo “tá tudo bem”?",
  "Já sorriu por educação?",
  "Já fingiu desapego?",
  "Já fingiu amor?",
  "Já fingiu indiferença?",
  "Já teve recaída emocional?",
  "Já teve recaída física?",
  "Já teve recaída digital?",
  "Já teve recaída sóbria?",
  "Já teve recaída bêbado(a)?",
  "Se pudesse apagar alguém da memória, apagaria?",
  "Se pudesse voltar para um ex, voltaria?",
  "Se pudesse mudar uma decisão, qual?",
  "Se pudesse mudar uma noite, qual?",
  "Se pudesse mudar um beijo, qual?",
  "Se pudesse mudar uma mensagem, qual?",
  "Se pudesse mudar uma transa, qual?",
  "Se pudesse mudar uma escolha, qual?",
  "Se pudesse mudar um erro, qual?",
  "Se pudesse mudar um medo, qual?",
  "Você se considera bom(a) na cama?",
  "Você se considera romântico(a)?",
  "Você se considera ciumento(a)?",
  "Você se considera intenso(a)?",
  "Você se considera desapegado(a)?",
  "Você se considera difícil?",
  "Você se considera carente?",
  "Você se considera confiante?",
  "Você se considera inseguro(a)?",
  "Você se considera sedutor(a)?",
  "Você se considera sincero(a)?",
  "Você se considera manipulador(a)?",
  "Você se considera fiel?",
  "Você se considera impulsivo(a)?",
  "Você se considera racional?",
  "Você se considera emocional?",
  "Você se considera vingativo(a)?",
  "Você se considera maduro(a)?",
  "Você se considera imaturo(a)?",
  "Você se considera intenso(a) demais?",
  "Você se considera frio(a) demais?",
  "Você se considera suficiente?",
  "Você se considera exagerado(a)?",
  "Você se considera verdadeiro(a)?",
  "Você se considera mentiroso(a)?",
  "Você se considera apaixonável?",
  "Você se considera esquecível?",
  "Você se considera marcante?",
  "Você se considera substituível?",
  "Você se considera inesquecível?",
  "Você se considera livre?",
  "Você se considera preso(a)?",
  "Você se considera feliz?",
  "Você se considera perdido(a)?",
  "Você se considera resolvido(a)?",
  "Você se considera confuso(a)?",
  "Você se considera desejável?",
  "Você se considera desejado(a)?",
  "Você se considera carismático(a)?",
  "Você se considera perigoso(a)?",
];

export default valeTudo;
